// Redrob icons - 260 glyphs.
//
// Generated by tools/generate/icons.js from the design system's reference bundle. The path geometry
// is transcribed, not rewritten: 24px box, 20px live area, 2px stroke, butt caps, miter joins, and
// every chevron, arrowhead and slash on the logo's 40 degree rake. Edit the design system and
// regenerate; a hand edit here is overwritten.
//
// Do not add a glyph from Feather, Lucide or any framework default. This set is the brand's own.

import * as React from 'react';

export type IconProps = React.SVGProps<SVGSVGElement>;

/** Every glyph shares this frame, so a glyph only carries its own geometry. */
export function svg(props: IconProps, children: React.ReactNode): React.ReactElement {
  return React.createElement(
    'svg',
    {
      viewBox: '0 0 24 24',
      width: '1em',
      height: '1em',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: 2,
      strokeLinecap: 'butt',
      strokeLinejoin: 'miter',
      strokeMiterlimit: 3,
      'aria-hidden': 'true',
      focusable: 'false',
      ...props,
    },
    children,
  );
}

const h = React.createElement;

export type IconName =
  | 'filePlus'
  | 'code'
  | 'terminal'
  | 'database'
  | 'server'
  | 'cloud'
  | 'cloudOff'
  | 'wifi'
  | 'wifiOff'
  | 'sync'
  | 'cpu'
  | 'api'
  | 'log'
  | 'plug'
  | 'power'
  | 'gauge'
  | 'package'
  | 'pulse'
  | 'monitor'
  | 'sun'
  | 'moon'
  | 'signIn'
  | 'signOut'
  | 'shieldCheck'
  | 'eyeOff'
  | 'zoomIn'
  | 'zoomOut'
  | 'userPlus'
  | 'userCheck'
  | 'userX'
  | 'userSearch'
  | 'userOff'
  | 'usersPlus'
  | 'hierarchy'
  | 'idCard'
  | 'permission'
  | 'resume'
  | 'interview'
  | 'invite'
  | 'roster'
  | 'timer'
  | 'clockAlert'
  | 'hourglass'
  | 'calendarPlus'
  | 'calendarCheck'
  | 'calendarX'
  | 'calendarRange'
  | 'calendarGrid'
  | 'calendarClock'
  | 'repeat'
  | 'alarm'
  | 'desk'
  | 'browser'
  | 'kanban'
  | 'pipeline'
  | 'target'
  | 'presentation'
  | 'mobile'
  | 'note'
  | 'book'
  | 'bookOpen'
  | 'lightbulb'
  | 'map'
  | 'barcode'
  | 'print'
  | 'qr'
  | 'move'
  | 'keyboard'
  | 'split'
  | 'merge'
  | 'dragHandle'
  | 'megaphone'
  | 'checkAll'
  | 'sliders'
  | 'accessibility'
  | 'message'
  | 'messages'
  | 'comment'
  | 'bell'
  | 'bellOff'
  | 'phone'
  | 'videoCall'
  | 'at'
  | 'hash'
  | 'share'
  | 'reply'
  | 'inbox'
  | 'draft'
  | 'image'
  | 'images'
  | 'camera'
  | 'video'
  | 'mic'
  | 'micOff'
  | 'volume'
  | 'volumeOff'
  | 'pause'
  | 'skipBack'
  | 'skipForward'
  | 'record'
  | 'help'
  | 'question'
  | 'alert'
  | 'bug'
  | 'verified'
  | 'pending'
  | 'blocked'
  | 'circleCheck'
  | 'circleX'
  | 'circlePlus'
  | 'circleMinus'
  | 'dot'
  | 'card'
  | 'wallet'
  | 'receipt'
  | 'tag'
  | 'cart'
  | 'percent'
  | 'coins'
  | 'bank'
  | 'invoice'
  | 'arrowUp'
  | 'arrowUpLeft'
  | 'arrowDownLeft'
  | 'arrowDownRight'
  | 'chevronsRight'
  | 'chevronsLeft'
  | 'chevronsUp'
  | 'chevronsDown'
  | 'home'
  | 'back'
  | 'forward'
  | 'expand'
  | 'collapse'
  | 'maximize'
  | 'minimize'
  | 'fullscreen'
  | 'sidebar'
  | 'panelRight'
  | 'layout'
  | 'fileText'
  | 'fileCode'
  | 'fileSheet'
  | 'fileImage'
  | 'fileZip'
  | 'filePdf'
  | 'folder'
  | 'folderOpen'
  | 'folderPlus'
  | 'archive'
  | 'clipboard'
  | 'clipboardCheck'
  | 'attachment'
  | 'save'
  | 'duplicate'
  | 'trash'
  | 'restore'
  | 'bold'
  | 'italic'
  | 'underline'
  | 'strikethrough'
  | 'list'
  | 'listOrdered'
  | 'indent'
  | 'outdent'
  | 'alignLeft'
  | 'alignCenter'
  | 'alignRight'
  | 'alignJustify'
  | 'undo'
  | 'redo'
  | 'crop'
  | 'door'
  | 'threshold'
  | 'passport'
  | 'check'
  | 'minus'
  | 'plus'
  | 'close'
  | 'chevronDown'
  | 'chevronUp'
  | 'chevronLeft'
  | 'chevronRight'
  | 'arrowRight'
  | 'arrowLeft'
  | 'arrowUpRight'
  | 'arrowDown'
  | 'external'
  | 'search'
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'stop'
  | 'sparkle'
  | 'tool'
  | 'shield'
  | 'globe'
  | 'key'
  | 'lock'
  | 'unlock'
  | 'user'
  | 'users'
  | 'ladder'
  | 'spark'
  | 'mail'
  | 'file'
  | 'grid'
  | 'chart'
  | 'trend'
  | 'clock'
  | 'calendar'
  | 'filter'
  | 'sort'
  | 'link'
  | 'upload'
  | 'download'
  | 'send'
  | 'refresh'
  | 'more'
  | 'menu'
  | 'settings'
  | 'eye'
  | 'star'
  | 'bookmark'
  | 'copy'
  | 'edit'
  | 'play'
  | 'bridge'
  | 'translate'
  | 'beacon'
  | 'seal'
  | 'clause'
  | 'highlight'
  | 'redact'
  | 'stack'
  | 'columns'
  | 'checklist'
  | 'signature'
  | 'scan'
  | 'scales'
  | 'flag'
  | 'compare'
  | 'route'
  | 'history'
  | 'branch'
  | 'briefcase'
  | 'building'
  | 'graduation'
  | 'network'
  | 'pin'
  | 'anonymous'
  | 'brush'
  | 'fill'
  | 'rectangle'
  | 'ellipse'
  | 'shape'
  | 'gradient'
  | 'transform'
  | 'eyedropper';

export type IconComponent = (props: IconProps) => React.ReactElement;

export const icons: Record<IconName, IconComponent> = {
  filePlus: (p) => svg(p, [h("path", { d: "M5.5 3H14L18.5 7.5V19.5A1.5 1.5 0 0 1 17 21H7A1.5 1.5 0 0 1 5.5 19.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.5 18.5 7.5" , key: "b" }), h("line", { x1: 12, y1: 11.8, x2: 12, y2: 17.8 , key: "c" }), h("line", { x1: 9, y1: 14.8, x2: 15, y2: 14.8 , key: "d" })]),
  code: (p) => svg(p, [h("polyline", { points: "9 7.8 4 12 9 16.2" , key: "a" }), h("polyline", { points: "15 7.8 20 12 15 16.2" , key: "b" })]),
  terminal: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("polyline", { points: "7 9.9 10 12.42 7 14.93" , key: "b" }), h("line", { x1: 12.5, y1: 14.93, x2: 17, y2: 14.93 , key: "c" })]),
  database: (p) => svg(p, [h("ellipse", { cx: 12, cy: 6, rx: 7, ry: 3 , key: "a" }), h("path", { d: "M5 6V18A7 3 0 0 0 19 18V6" , key: "b" }), h("path", { d: "M5 12A7 3 0 0 0 19 12" , key: "c" })]),
  server: (p) => svg(p, [h("path", { d: "M3 4H19A2 2 0 0 1 21 6V9A2 2 0 0 1 19 11H5A2 2 0 0 1 3 9Z" , key: "a" }), h("path", { d: "M3 13H19A2 2 0 0 1 21 15V18A2 2 0 0 1 19 20H5A2 2 0 0 1 3 18Z" , key: "b" }), h("rect", { x: 6, y: 6.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 6, y: 15.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" }), h("line", { x1: 11, y1: 7.5, x2: 18, y2: 7.5 , key: "e" }), h("line", { x1: 11, y1: 16.5, x2: 18, y2: 16.5 , key: "f" })]),
  cloud: (p) => svg(p, h("path", { d: "M7.5 18.5H17A3.5 3.5 0 0 0 17 11.5A5.5 5.5 0 0 0 6.6 12.3A3.2 3.2 0 0 0 7.5 18.5Z" , key: "a" })),
  cloudOff: (p) => svg(p, [h("path", { d: "M7.5 18.5H17A3.5 3.5 0 0 0 17 11.5A5.5 5.5 0 0 0 6.6 12.3A3.2 3.2 0 0 0 7.5 18.5Z" , key: "a" }), h("line", { x1: 4.5, y1: 6.5, x2: 19.5, y2: 19.09 , key: "b" })]),
  wifi: (p) => svg(p, [h("path", { d: "M4.34 13.07A10 10 0 0 1 19.66 13.07" , key: "a" }), h("path", { d: "M7.1 15.39A6.4 6.4 0 0 1 16.9 15.39" , key: "b" }), h("path", { d: "M9.85 17.7A2.8 2.8 0 0 1 14.15 17.7" , key: "c" }), h("circle", { cx: 12, cy: 19.5, r: 1.4, fill: "currentColor", stroke: "none" , key: "d" })]),
  wifiOff: (p) => svg(p, [h("path", { d: "M4.34 13.07A10 10 0 0 1 19.66 13.07" , key: "a" }), h("path", { d: "M7.1 15.39A6.4 6.4 0 0 1 16.9 15.39" , key: "b" }), h("path", { d: "M9.85 17.7A2.8 2.8 0 0 1 14.15 17.7" , key: "c" }), h("circle", { cx: 12, cy: 19.5, r: 1.4, fill: "currentColor", stroke: "none" , key: "d" }), h("line", { x1: 4.5, y1: 6.5, x2: 19.5, y2: 19.09 , key: "e" })]),
  sync: (p) => svg(p, [h("path", { d: "M12 5.5A6.5 6.5 0 0 1 18.5 12" , key: "a" }), h("polyline", { points: "16.57 9.7 18.5 12 20.43 9.7" , key: "b" }), h("path", { d: "M12 18.5A6.5 6.5 0 0 1 5.5 12" , key: "c" }), h("polyline", { points: "7.43 14.3 5.5 12 3.57 14.3" , key: "d" })]),
  cpu: (p) => svg(p, [h("path", { d: "M6 6H16A2 2 0 0 1 18 8V16A2 2 0 0 1 16 18H8A2 2 0 0 1 6 16Z" , key: "a" }), h("rect", { x: 9.5, y: 9.5, width: 5, height: 5 , key: "b" }), h("line", { x1: 9.5, y1: 3, x2: 9.5, y2: 6 , key: "c" }), h("line", { x1: 14.5, y1: 3, x2: 14.5, y2: 6 , key: "d" }), h("line", { x1: 9.5, y1: 18, x2: 9.5, y2: 21 , key: "e" }), h("line", { x1: 14.5, y1: 18, x2: 14.5, y2: 21 , key: "f" }), h("line", { x1: 3, y1: 9.5, x2: 6, y2: 9.5 , key: "g" }), h("line", { x1: 3, y1: 14.5, x2: 6, y2: 14.5 , key: "h" }), h("line", { x1: 18, y1: 9.5, x2: 21, y2: 9.5 , key: "i" }), h("line", { x1: 18, y1: 14.5, x2: 21, y2: 14.5 , key: "j" })]),
  api: (p) => svg(p, [h("path", { d: "M9.5 4.5A2.5 2.5 0 0 0 7 7V10A2 2 0 0 1 5 12A2 2 0 0 1 7 14V17A2.5 2.5 0 0 0 9.5 19.5" , key: "a" }), h("path", { d: "M14.5 4.5A2.5 2.5 0 0 1 17 7V10A2 2 0 0 0 19 12A2 2 0 0 0 17 14V17A2.5 2.5 0 0 1 14.5 19.5" , key: "b" })]),
  log: (p) => svg(p, [h("line", { x1: 3.5, y1: 7, x2: 7.5, y2: 7 , key: "a" }), h("line", { x1: 10, y1: 7, x2: 20.5, y2: 7 , key: "b" }), h("line", { x1: 3.5, y1: 12, x2: 7.5, y2: 12 , key: "c" }), h("line", { x1: 10, y1: 12, x2: 20.5, y2: 12 , key: "d" }), h("line", { x1: 3.5, y1: 17, x2: 7.5, y2: 17 , key: "e" }), h("line", { x1: 10, y1: 17, x2: 20.5, y2: 17 , key: "f" })]),
  plug: (p) => svg(p, [h("line", { x1: 9, y1: 3.5, x2: 9, y2: 8 , key: "a" }), h("line", { x1: 15, y1: 3.5, x2: 15, y2: 8 , key: "b" }), h("path", { d: "M6.5 8H17.5V12A5.5 5.5 0 0 1 6.5 12Z" , key: "c" }), h("line", { x1: 12, y1: 17.5, x2: 12, y2: 20.5 , key: "d" })]),
  power: (p) => svg(p, [h("path", { d: "M7.08 5.7A8 8 0 1 0 16.92 5.7" , key: "a" }), h("line", { x1: 12, y1: 3, x2: 12, y2: 11.5 , key: "b" })]),
  gauge: (p) => svg(p, [h("path", { d: "M4 16A8 8 0 0 1 20 16" , key: "a" }), h("line", { x1: 12, y1: 16, x2: 7.02, y2: 11.82 , key: "b" }), h("circle", { cx: 12, cy: 16, r: 1.6, fill: "currentColor", stroke: "none" , key: "c" })]),
  package: (p) => svg(p, [h("path", { d: "M3.5 8H20.5V19A1.5 1.5 0 0 1 19 20.5H5A1.5 1.5 0 0 1 3.5 19Z" , key: "a" }), h("polyline", { points: "3.5 8 6 4 18 4 20.5 8" , key: "b" }), h("line", { x1: 12, y1: 4, x2: 12, y2: 20.5 , key: "c" })]),
  pulse: (p) => svg(p, h("polyline", { points: "3 12 7.5 12 9.5 6.5 13 17.5 15 12 21 12" , key: "a" })),
  monitor: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V14.5A2 2 0 0 1 19 16.5H5A2 2 0 0 1 3 14.5Z" , key: "a" }), h("line", { x1: 12, y1: 16.5, x2: 12, y2: 20 , key: "b" }), h("line", { x1: 8, y1: 20, x2: 16, y2: 20 , key: "c" })]),
  sun: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 3.2, key: "a" }), h("line", { x1: 17.8, y1: 12.0, x2: 21.2, y2: 12.0, key: "b" }), h("line", { x1: 16.44, y1: 8.27, x2: 19.05, y2: 6.09, key: "c" }), h("line", { x1: 12.0, y1: 6.2, x2: 12.0, y2: 2.8, key: "d" }), h("line", { x1: 7.56, y1: 8.27, x2: 4.95, y2: 6.09, key: "e" }), h("line", { x1: 6.2, y1: 12.0, x2: 2.8, y2: 12.0, key: "f" }), h("line", { x1: 7.56, y1: 15.73, x2: 4.95, y2: 17.91, key: "g" }), h("line", { x1: 12.0, y1: 17.8, x2: 12.0, y2: 21.2, key: "h" }), h("line", { x1: 16.44, y1: 15.73, x2: 19.05, y2: 17.91, key: "i" })]),
  moon: (p) => svg(p, h("path", { d: "M15.2 3.6A8.6 8.6 0 1 0 20.4 15.4A6.9 6.9 0 0 1 15.2 3.6Z", key: "a" })),
  signIn: (p) => svg(p, [h("path", { d: "M13.5 3.5H18.5A2 2 0 0 1 20.5 5.5V18.5A2 2 0 0 1 18.5 20.5H13.5" , key: "a" }), h("line", { x1: 3.5, y1: 12, x2: 12, y2: 12 , key: "b" }), h("polyline", { points: "8.78 14.7 12 12 8.78 9.3" , key: "c" })]),
  signOut: (p) => svg(p, [h("path", { d: "M10.5 3.5H5.5A2 2 0 0 0 3.5 5.5V18.5A2 2 0 0 0 5.5 20.5H10.5" , key: "a" }), h("line", { x1: 9, y1: 12, x2: 20, y2: 12 , key: "b" }), h("polyline", { points: "16.78 14.7 20 12 16.78 9.3" , key: "c" })]),
  shieldCheck: (p) => svg(p, [h("path", { d: "M12 3.4 19.6 6.3 V12.4 C19.6 16.6 16.2 19.4 12 20.6 C7.8 19.4 4.4 16.6 4.4 12.4 V6.3 Z" , key: "a" }), h("polyline", { points: "8 12.2 10.5 14.3 16 9.68" , key: "b" })]),
  eyeOff: (p) => svg(p, [h("path", { d: "M9.1 6.5C10 6.2 11 6 12 6C15.6 6 19 8 21.5 12C20.5 13.6 19.4 14.9 18.1 15.9" , key: "a" }), h("path", { d: "M14.8 17.6C13.9 17.9 13 18 12 18C8.4 18 5 16 2.5 12C3.7 10.1 5.1 8.6 6.6 7.5" , key: "b" }), h("line", { x1: 4.5, y1: 4.5, x2: 19.5, y2: 17.09 , key: "c" })]),
  zoomIn: (p) => svg(p, [h("path", { d: "M12.84 16.02 A6 6 0 1 1 16.35 11.85" , key: "a" }), h("line", { x1: 15.1, y1: 14.36, x2: 20.5, y2: 18.89 , key: "b" }), h("line", { x1: 7.5, y1: 10.5, x2: 13.5, y2: 10.5 , key: "c" }), h("line", { x1: 10.5, y1: 7.5, x2: 10.5, y2: 13.5 , key: "d" })]),
  zoomOut: (p) => svg(p, [h("path", { d: "M12.84 16.02 A6 6 0 1 1 16.35 11.85" , key: "a" }), h("line", { x1: 15.1, y1: 14.36, x2: 20.5, y2: 18.89 , key: "b" }), h("line", { x1: 7.5, y1: 10.5, x2: 13.5, y2: 10.5 , key: "c" })]),
  userPlus: (p) => svg(p, [h("path", { d: "M13.06 7.44 A3.6 3.6 0 1 1 10.67 4.6" , key: "a" }), h("path", { d: "M3 20.5C3 17.4 5.9 15.2 9.5 15.2C13.1 15.2 16 17.4 16 20.5" , key: "b" }), h("line", { x1: 18.5, y1: 3.7, x2: 18.5, y2: 9.3 , key: "c" }), h("line", { x1: 15.7, y1: 6.5, x2: 21.3, y2: 6.5 , key: "d" })]),
  userCheck: (p) => svg(p, [h("path", { d: "M13.06 7.44 A3.6 3.6 0 1 1 10.67 4.6" , key: "a" }), h("path", { d: "M3 20.5C3 17.4 5.9 15.2 9.5 15.2C13.1 15.2 16 17.4 16 20.5" , key: "b" }), h("polyline", { points: "15.6 6.4 17.6 8.08 21 5.22" , key: "c" })]),
  userX: (p) => svg(p, [h("path", { d: "M13.06 7.44 A3.6 3.6 0 1 1 10.67 4.6" , key: "a" }), h("path", { d: "M3 20.5C3 17.4 5.9 15.2 9.5 15.2C13.1 15.2 16 17.4 16 20.5" , key: "b" }), h("line", { x1: 16.3, y1: 4.3, x2: 20.7, y2: 8.7 , key: "c" }), h("line", { x1: 20.7, y1: 4.3, x2: 16.3, y2: 8.7 , key: "d" })]),
  userSearch: (p) => svg(p, [h("path", { d: "M11.16 8 A3.2 3.2 0 1 1 9.04 5.47" , key: "a" }), h("path", { d: "M2.5 20.5C2.5 17.8 4.9 15.9 8 15.9C11.1 15.9 13.5 17.8 13.5 20.5" , key: "b" }), h("path", { d: "M13.4 9.5A3.4 3.4 0 1 1 20.2 9.5A3.4 3.4 0 1 1 13.4 9.5" , key: "c" }), h("line", { x1: 19.2, y1: 11.9, x2: 20.8, y2: 13.24 , key: "d" })]),
  userOff: (p) => svg(p, [h("path", { d: "M8 8A4 4 0 1 1 16 8A4 4 0 1 1 8 8" , key: "a" }), h("path", { d: "M4.5 20.5C4.5 16.9 7.9 14.5 12 14.5C16.1 14.5 19.5 16.9 19.5 20.5" , key: "b" }), h("line", { x1: 4.5, y1: 4.5, x2: 19.5, y2: 17.09 , key: "c" })]),
  usersPlus: (p) => svg(p, [h("path", { d: "M13.06 7.44 A3.6 3.6 0 1 1 10.67 4.6" , key: "a" }), h("path", { d: "M3 20.5C3 17.4 5.9 15.2 9.5 15.2C13.1 15.2 16 17.4 16 20.5" , key: "b" }), h("path", { d: "M16.2 5.2A3.6 3.6 0 0 1 16.2 11.9" , key: "c" }), h("line", { x1: 18.5, y1: 15.5, x2: 18.5, y2: 20.5 , key: "d" }), h("line", { x1: 16, y1: 18, x2: 21, y2: 18 , key: "e" })]),
  hierarchy: (p) => svg(p, [h("path", { d: "M9 3H13A2 2 0 0 1 15 5V5.5A2 2 0 0 1 13 7.5H11A2 2 0 0 1 9 5.5Z" , key: "a" }), h("line", { x1: 12, y1: 7.5, x2: 12, y2: 10.5 , key: "b" }), h("line", { x1: 6, y1: 10.5, x2: 18, y2: 10.5 , key: "c" }), h("line", { x1: 6, y1: 10.5, x2: 6, y2: 13.5 , key: "d" }), h("line", { x1: 18, y1: 10.5, x2: 18, y2: 13.5 , key: "e" }), h("path", { d: "M3 13.5H7A2 2 0 0 1 9 15.5V16A2 2 0 0 1 7 18H5A2 2 0 0 1 3 16Z" , key: "f" }), h("path", { d: "M15 13.5H19A2 2 0 0 1 21 15.5V16A2 2 0 0 1 19 18H17A2 2 0 0 1 15 16Z" , key: "g" })]),
  idCard: (p) => svg(p, [h("path", { d: "M3 5H19A2 2 0 0 1 21 7V17A2 2 0 0 1 19 19H5A2 2 0 0 1 3 17Z" , key: "a" }), h("path", { d: "M10.37 10.12 A2.4 2.4 0 1 1 8.78 8.23" , key: "b" }), h("path", { d: "M4.8 15.8C4.8 14 6.2 12.9 8 12.9C9.8 12.9 11.2 14 11.2 15.8" , key: "c" }), h("line", { x1: 13.5, y1: 10, x2: 18.5, y2: 10 , key: "d" }), h("line", { x1: 13.5, y1: 13.5, x2: 18.5, y2: 13.5 , key: "e" })]),
  permission: (p) => svg(p, [h("path", { d: "M8 10.5V8A4 4 0 0 1 16 8V10.5" , key: "a" }), h("path", { d: "M4.5 10.5H17.5A2 2 0 0 1 19.5 12.5V18.5A2 2 0 0 1 17.5 20.5H6.5A2 2 0 0 1 4.5 18.5Z" , key: "b" }), h("polyline", { points: "8.5 15.5 10.7 17.35 15.5 13.32" , key: "c" })]),
  resume: (p) => svg(p, [h("path", { d: "M5.5 3H14L18.5 7.5V19.5A1.5 1.5 0 0 1 17 21H7A1.5 1.5 0 0 1 5.5 19.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.5 18.5 7.5" , key: "b" }), h("path", { d: "M9.5 11.4A2.2 2.2 0 1 1 13.9 11.4A2.2 2.2 0 1 1 9.5 11.4" , key: "c" }), h("path", { d: "M8.4 17.4C8.4 15.3 9.9 14.2 11.7 14.2C13.5 14.2 15 15.3 15 17.4" , key: "d" })]),
  interview: (p) => svg(p, [h("path", { d: "M10.36 7.35 A2.9 2.9 0 1 1 8.44 5.06" , key: "a" }), h("path", { d: "M4.2 16C4.2 13.7 5.7 12.4 7.5 12.4C9.3 12.4 10.8 13.7 10.8 16" , key: "b" }), h("path", { d: "M19.36 7.35 A2.9 2.9 0 1 1 17.44 5.06" , key: "c" }), h("path", { d: "M13.2 16C13.2 13.7 14.7 12.4 16.5 12.4C18.3 12.4 19.8 13.7 19.8 16" , key: "d" }), h("line", { x1: 3, y1: 19, x2: 21, y2: 19 , key: "e" })]),
  invite: (p) => svg(p, [h("path", { d: "M3 4.5H15A2 2 0 0 1 17 6.5V14.5A2 2 0 0 1 15 16.5H5A2 2 0 0 1 3 14.5Z" , key: "a" }), h("polyline", { points: "3 6.8 10 11.3 17 6.8" , key: "b" }), h("line", { x1: 19, y1: 17, x2: 19, y2: 21 , key: "c" }), h("line", { x1: 17, y1: 19, x2: 21, y2: 19 , key: "d" })]),
  roster: (p) => svg(p, [h("path", { d: "M3.6 6A1.9 1.9 0 1 1 7.4 6A1.9 1.9 0 1 1 3.6 6" , key: "a" }), h("line", { x1: 9.5, y1: 6, x2: 20.5, y2: 6 , key: "b" }), h("path", { d: "M3.6 12A1.9 1.9 0 1 1 7.4 12A1.9 1.9 0 1 1 3.6 12" , key: "c" }), h("line", { x1: 9.5, y1: 12, x2: 20.5, y2: 12 , key: "d" }), h("path", { d: "M3.6 18A1.9 1.9 0 1 1 7.4 18A1.9 1.9 0 1 1 3.6 18" , key: "e" }), h("line", { x1: 9.5, y1: 18, x2: 20.5, y2: 18 , key: "f" })]),
  timer: (p) => svg(p, [h("path", { d: "M4.5 13.5A7.5 7.5 0 1 1 19.5 13.5A7.5 7.5 0 1 1 4.5 13.5" , key: "a" }), h("line", { x1: 12, y1: 3.5, x2: 12, y2: 6 , key: "b" }), h("line", { x1: 9.5, y1: 3.5, x2: 14.5, y2: 3.5 , key: "c" }), h("line", { x1: 12, y1: 13.5, x2: 12, y2: 8.8 , key: "d" })]),
  clockAlert: (p) => svg(p, [h("path", { d: "M3.7 12A6.8 6.8 0 1 1 17.3 12A6.8 6.8 0 1 1 3.7 12" , key: "a" }), h("polyline", { points: "10.5 7.6 10.5 12.3 13.9 14" , key: "b" }), h("line", { x1: 19.5, y1: 13, x2: 19.5, y2: 17 , key: "c" }), h("rect", { x: 18.5, y: 18.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" })]),
  hourglass: (p) => svg(p, h("path", { d: "M6.5 3.5H17.5V7.385L12 12 17.5 16.615V20.5H6.5V16.615L12 12 6.5 7.385Z" , key: "a" })),
  calendarPlus: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z" , key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10 , key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7 , key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7 , key: "d" }), h("line", { x1: 12, y1: 12.5, x2: 12, y2: 18 , key: "e" }), h("line", { x1: 8.75, y1: 15.25, x2: 15.25, y2: 15.25 , key: "f" })]),
  calendarCheck: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z" , key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10 , key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7 , key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7 , key: "d" }), h("polyline", { points: "8.3 15.1 10.9 17.28 15.9 13.08" , key: "e" })]),
  calendarX: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z" , key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10 , key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7 , key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7 , key: "d" }), h("line", { x1: 9.2, y1: 12.7, x2: 14.8, y2: 18.3 , key: "e" }), h("line", { x1: 14.8, y1: 12.7, x2: 9.2, y2: 18.3 , key: "f" })]),
  calendarRange: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z" , key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10 , key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7 , key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7 , key: "d" }), h("rect", { x: 7, y: 14, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "e" }), h("rect", { x: 15, y: 14, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "f" }), h("line", { x1: 9, y1: 15, x2: 15, y2: 15 , key: "g" })]),
  calendarGrid: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z" , key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10 , key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7 , key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7 , key: "d" }), h("rect", { x: 6.5, y: 12.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "e" }), h("rect", { x: 11, y: 12.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "f" }), h("rect", { x: 15.5, y: 12.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "g" }), h("rect", { x: 6.5, y: 16.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "h" }), h("rect", { x: 11, y: 16.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "i" })]),
  calendarClock: (p) => svg(p, [h("path", { d: "M17.5 11.5V7A2 2 0 0 0 15.5 5H3.5V16.5A2 2 0 0 0 5.5 18.5H11" , key: "a" }), h("line", { x1: 3.5, y1: 9.5, x2: 17.5, y2: 9.5 , key: "b" }), h("line", { x1: 7, y1: 3, x2: 7, y2: 6.5 , key: "c" }), h("line", { x1: 14, y1: 3, x2: 14, y2: 6.5 , key: "d" }), h("path", { d: "M12.8 16.5A4 4 0 1 1 20.8 16.5A4 4 0 1 1 12.8 16.5" , key: "e" }), h("polyline", { points: "16.8 14.2 16.8 16.5 18.6 17.4" , key: "f" })]),
  repeat: (p) => svg(p, [h("path", { d: "M4.5 11V9.5A2.5 2.5 0 0 1 7 7H17" , key: "a" }), h("polyline", { points: "13.78 9.7 17 7 13.78 4.3" , key: "b" }), h("path", { d: "M19.5 13V14.5A2.5 2.5 0 0 1 17 17H7" , key: "c" }), h("polyline", { points: "10.22 14.3 7 17 10.22 19.7" , key: "d" })]),
  alarm: (p) => svg(p, [h("path", { d: "M5 13.5A7 7 0 1 1 19 13.5A7 7 0 1 1 5 13.5" , key: "a" }), h("path", { d: "M3.5 7.4A4 4 0 0 1 7.4 4.3" , key: "b" }), h("path", { d: "M20.5 7.4A4 4 0 0 0 16.6 4.3" , key: "c" }), h("polyline", { points: "12 9.3 12 13.5 15.2 15.2" , key: "d" })]),
  desk: (p) => svg(p, [h("line", { x1: 3, y1: 11, x2: 21, y2: 11 , key: "a" }), h("line", { x1: 5.5, y1: 11, x2: 5.5, y2: 20.5 , key: "b" }), h("line", { x1: 18.5, y1: 11, x2: 18.5, y2: 20.5 , key: "c" }), h("path", { d: "M9 4H13A2 2 0 0 1 15 6V7A2 2 0 0 1 13 9H11A2 2 0 0 1 9 7Z" , key: "d" }), h("line", { x1: 12, y1: 9, x2: 12, y2: 11 , key: "e" })]),
  browser: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("line", { x1: 3, y1: 9, x2: 21, y2: 9 , key: "b" }), h("rect", { x: 5.5, y: 6.2, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 8.3, y: 6.2, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "d" })]),
  kanban: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("line", { x1: 9, y1: 4.5, x2: 9, y2: 19.5 , key: "b" }), h("line", { x1: 15, y1: 4.5, x2: 15, y2: 19.5 , key: "c" }), h("rect", { x: 4.5, y: 7.5, width: 3, height: 1.8, fill: "currentColor", stroke: "none" , key: "d" }), h("rect", { x: 4.5, y: 11, width: 3, height: 1.8, fill: "currentColor", stroke: "none" , key: "e" }), h("rect", { x: 10.5, y: 7.5, width: 3, height: 1.8, fill: "currentColor", stroke: "none" , key: "f" }), h("rect", { x: 16.5, y: 7.5, width: 3, height: 1.8, fill: "currentColor", stroke: "none" , key: "g" })]),
  pipeline: (p) => svg(p, [h("line", { x1: 3, y1: 4.5, x2: 3, y2: 19.5 , key: "a" }), h("rect", { x: 5.5, y: 5, width: 15, height: 3, fill: "currentColor", stroke: "none" , key: "b" }), h("rect", { x: 5.5, y: 10.5, width: 11, height: 3, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 5.5, y: 16, width: 7, height: 3, fill: "currentColor", stroke: "none" , key: "d" })]),
  target: (p) => svg(p, [h("path", { d: "M3.5 12A8.5 8.5 0 1 1 20.5 12A8.5 8.5 0 1 1 3.5 12" , key: "a" }), h("path", { d: "M7.5 12A4.5 4.5 0 1 1 16.5 12A4.5 4.5 0 1 1 7.5 12" , key: "b" }), h("circle", { cx: 12, cy: 12, r: 1.8, fill: "currentColor", stroke: "none" , key: "c" })]),
  presentation: (p) => svg(p, [h("path", { d: "M3 3.5H19A2 2 0 0 1 21 5.5V13A2 2 0 0 1 19 15H5A2 2 0 0 1 3 13Z" , key: "a" }), h("line", { x1: 12, y1: 15, x2: 12, y2: 18 , key: "b" }), h("line", { x1: 8.5, y1: 20.5, x2: 15.5, y2: 20.5 , key: "c" }), h("line", { x1: 8, y1: 12, x2: 8, y2: 9 , key: "d" }), h("line", { x1: 12, y1: 12, x2: 12, y2: 7 , key: "e" }), h("line", { x1: 16, y1: 12, x2: 16, y2: 10 , key: "f" })]),
  mobile: (p) => svg(p, [h("path", { d: "M7 3H15A2 2 0 0 1 17 5V19A2 2 0 0 1 15 21H9A2 2 0 0 1 7 19Z" , key: "a" }), h("line", { x1: 10.5, y1: 17.5, x2: 13.5, y2: 17.5 , key: "b" })]),
  note: (p) => svg(p, [h("path", { d: "M4 3.5H20V15.5L14.5 21H5.5A1.5 1.5 0 0 1 4 19.5Z" , key: "a" }), h("polyline", { points: "20 15.5 14.5 15.5 14.5 21" , key: "b" }), h("line", { x1: 7, y1: 8, x2: 17, y2: 8 , key: "c" }), h("line", { x1: 7, y1: 11.5, x2: 17, y2: 11.5 , key: "d" })]),
  book: (p) => svg(p, [h("path", { d: "M4.5 3.5H17.5A2 2 0 0 1 19.5 5.5V18.5A2 2 0 0 1 17.5 20.5H6.5A2 2 0 0 1 4.5 18.5Z" , key: "a" }), h("line", { x1: 8, y1: 3.5, x2: 8, y2: 20.5 , key: "b" }), h("line", { x1: 10.8, y1: 8, x2: 16.8, y2: 8 , key: "c" }), h("line", { x1: 10.8, y1: 11.5, x2: 15, y2: 11.5 , key: "d" })]),
  bookOpen: (p) => svg(p, [h("path", { d: "M12 7.2C10.6 5.9 8.4 5 6 5H3.5V17.5H6C8.4 17.5 10.6 18.4 12 19.7" , key: "a" }), h("path", { d: "M12 7.2C13.4 5.9 15.6 5 18 5H20.5V17.5H18C15.6 17.5 13.4 18.4 12 19.7" , key: "b" })]),
  lightbulb: (p) => svg(p, [h("path", { d: "M8.6 15.4A5.6 5.6 0 1 1 15.4 15.4V17.5H8.6Z" , key: "a" }), h("line", { x1: 9.5, y1: 19.5, x2: 14.5, y2: 19.5 , key: "b" }), h("line", { x1: 10.5, y1: 21, x2: 13.5, y2: 21 , key: "c" })]),
  map: (p) => svg(p, [h("polyline", { points: "3.5 6.5 9 4 15 7 20.5 4.5 20.5 17.5 15 20 9 17 3.5 19.5 3.5 6.5" , key: "a" }), h("line", { x1: 9, y1: 4, x2: 9, y2: 17 , key: "b" }), h("line", { x1: 15, y1: 7, x2: 15, y2: 20 , key: "c" })]),
  barcode: (p) => svg(p, [h("rect", { x: 3.5, y: 5, width: 1.5, height: 14, fill: "currentColor", stroke: "none" , key: "a" }), h("line", { x1: 7, y1: 5, x2: 7, y2: 19 , key: "b" }), h("rect", { x: 9, y: 5, width: 2.5, height: 14, fill: "currentColor", stroke: "none" , key: "c" }), h("line", { x1: 13, y1: 5, x2: 13, y2: 19 , key: "d" }), h("line", { x1: 15, y1: 5, x2: 15, y2: 19 , key: "e" }), h("rect", { x: 17, y: 5, width: 1.5, height: 14, fill: "currentColor", stroke: "none" , key: "f" }), h("line", { x1: 20, y1: 5, x2: 20, y2: 19 , key: "g" })]),
  print: (p) => svg(p, [h("path", { d: "M7 8V3.5H17V8" , key: "a" }), h("path", { d: "M3.5 8H18.5A2 2 0 0 1 20.5 10V14A2 2 0 0 1 18.5 16H5.5A2 2 0 0 1 3.5 14Z" , key: "b" }), h("path", { d: "M7 14H17V20.5H7Z" , key: "c" }), h("rect", { x: 16.5, y: 10.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" })]),
  qr: (p) => svg(p, [h("rect", { x: 3.5, y: 3.5, width: 6, height: 6 , key: "a" }), h("rect", { x: 5.5, y: 5.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "b" }), h("rect", { x: 14.5, y: 3.5, width: 6, height: 6 , key: "c" }), h("rect", { x: 16.5, y: 5.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" }), h("rect", { x: 3.5, y: 14.5, width: 6, height: 6 , key: "e" }), h("rect", { x: 5.5, y: 16.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "f" }), h("rect", { x: 14.5, y: 14.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "g" }), h("rect", { x: 18.5, y: 18.5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "h" })]),
  move: (p) => svg(p, [h("line", { x1: 12, y1: 4, x2: 12, y2: 20 , key: "a" }), h("line", { x1: 4, y1: 12, x2: 20, y2: 12 , key: "b" }), h("polyline", { points: "14.06 6.45 12 4 9.94 6.45" , key: "c" }), h("polyline", { points: "9.94 17.55 12 20 14.06 17.55" , key: "d" }), h("polyline", { points: "6.45 9.94 4 12 6.45 14.06" , key: "e" }), h("polyline", { points: "17.55 14.06 20 12 17.55 9.94" , key: "f" })]),
  keyboard: (p) => svg(p, [h("path", { d: "M3 6.5H19A2 2 0 0 1 21 8.5V15.5A2 2 0 0 1 19 17.5H5A2 2 0 0 1 3 15.5Z" , key: "a" }), h("rect", { x: 6, y: 9.5, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "b" }), h("rect", { x: 9.5, y: 9.5, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 13, y: 9.5, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "d" }), h("rect", { x: 16.5, y: 9.5, width: 1.6, height: 1.6, fill: "currentColor", stroke: "none" , key: "e" }), h("line", { x1: 8, y1: 14.5, x2: 16, y2: 14.5 , key: "f" })]),
  split: (p) => svg(p, [h("line", { x1: 3.5, y1: 12, x2: 13, y2: 12 , key: "a" }), h("path", { d: "M13 12A2 2 0 0 0 15 10V7H20.5" , key: "b" }), h("path", { d: "M13 12A2 2 0 0 1 15 14V17H20.5" , key: "c" })]),
  merge: (p) => svg(p, [h("line", { x1: 11, y1: 12, x2: 20.5, y2: 12 , key: "a" }), h("path", { d: "M11 12A2 2 0 0 1 9 10V7H3.5" , key: "b" }), h("path", { d: "M11 12A2 2 0 0 0 9 14V17H3.5" , key: "c" })]),
  dragHandle: (p) => svg(p, [h("rect", { x: 8.5, y: 5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "a" }), h("rect", { x: 13.5, y: 5, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "b" }), h("rect", { x: 8.5, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 13.5, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" }), h("rect", { x: 8.5, y: 17, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "e" }), h("rect", { x: 13.5, y: 17, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "f" })]),
  megaphone: (p) => svg(p, [h("path", { d: "M4 9.5 17 4.5V19.5L4 14.5Z" , key: "a" }), h("path", { d: "M7.5 16V19.5A1.5 1.5 0 0 0 10.5 19.5V17.3" , key: "b" }), h("line", { x1: 19, y1: 10, x2: 21, y2: 10 , key: "c" }), h("line", { x1: 19, y1: 14, x2: 21, y2: 14 , key: "d" })]),
  checkAll: (p) => svg(p, [h("polyline", { points: "3 12.3 7 15.66 14 9.79" , key: "a" }), h("polyline", { points: "10 12.3 14 15.66 21 9.79" , key: "b" })]),
  sliders: (p) => svg(p, [h("line", { x1: 3.5, y1: 7, x2: 20.5, y2: 7 , key: "a" }), h("rect", { x: 8, y: 5.5, width: 3, height: 3, fill: "currentColor", stroke: "none" , key: "b" }), h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12 , key: "c" }), h("rect", { x: 13, y: 10.5, width: 3, height: 3, fill: "currentColor", stroke: "none" , key: "d" }), h("line", { x1: 3.5, y1: 17, x2: 20.5, y2: 17 , key: "e" }), h("rect", { x: 6, y: 15.5, width: 3, height: 3, fill: "currentColor", stroke: "none" , key: "f" })]),
  accessibility: (p) => svg(p, [h("circle", { cx: 12, cy: 5.5, r: 2, fill: "currentColor", stroke: "none" , key: "a" }), h("line", { x1: 4.5, y1: 9.5, x2: 19.5, y2: 9.5 , key: "b" }), h("line", { x1: 12, y1: 9.5, x2: 12, y2: 14 , key: "c" }), h("polyline", { points: "6.55 20.5 12 14 17.45 20.5" , key: "d" })]),
  message: (p) => svg(p, h("path", { d: "M4 6.5A1.5 1.5 0 0 1 5.5 5H18.5A1.5 1.5 0 0 1 20 6.5V15.5A1.5 1.5 0 0 1 18.5 17H9.4L5 20.5V17H5.5A1.5 1.5 0 0 1 4 15.5Z" , key: "a" })),
  messages: (p) => svg(p, [h("path", { d: "M3 5.5A1.5 1.5 0 0 1 4.5 4H15.5A1.5 1.5 0 0 1 17 5.5V12.5A1.5 1.5 0 0 1 15.5 14H8L4.5 17V14A1.5 1.5 0 0 1 3 12.5Z" , key: "a" }), h("path", { d: "M20 8.5A1.5 1.5 0 0 1 21 10V17A1.5 1.5 0 0 1 19.5 18.5V21L16 18.5H10.5" , key: "b" })]),
  comment: (p) => svg(p, [h("path", { d: "M4 6.5A1.5 1.5 0 0 1 5.5 5H18.5A1.5 1.5 0 0 1 20 6.5V15.5A1.5 1.5 0 0 1 18.5 17H9.4L5 20.5V17H5.5A1.5 1.5 0 0 1 4 15.5Z" , key: "a" }), h("line", { x1: 8, y1: 9.5, x2: 16, y2: 9.5 , key: "b" }), h("line", { x1: 8, y1: 12.8, x2: 13, y2: 12.8 , key: "c" })]),
  bell: (p) => svg(p, [h("path", { d: "M7 10.5A5 5 0 0 1 17 10.5V15L19 18H5L7 15Z" , key: "a" }), h("path", { d: "M10 18V19A2 2 0 0 0 14 19V18" , key: "b" })]),
  bellOff: (p) => svg(p, [h("path", { d: "M7 10.5A5 5 0 0 1 12.8 5.6" , key: "a" }), h("path", { d: "M17 11.6V15L19 18H8" , key: "b" }), h("path", { d: "M5 18L7 15V12" , key: "c" }), h("path", { d: "M10 18V19A2 2 0 0 0 14 19V18" , key: "d" }), h("line", { x1: 4.5, y1: 4.5, x2: 19.5, y2: 17.09 , key: "e" })]),
  phone: (p) => svg(p, h("path", { d: "M6.5 3.5H10L11.5 8 9.3 9.6A11 11 0 0 0 14.4 14.7L16 12.5 20.5 14V17.5A2.5 2.5 0 0 1 18 20C10.3 19.6 4.4 13.7 4 6A2.5 2.5 0 0 1 6.5 3.5Z" , key: "a" })),
  videoCall: (p) => svg(p, [h("path", { d: "M3 6H13A2 2 0 0 1 15 8V16A2 2 0 0 1 13 18H5A2 2 0 0 1 3 16Z" , key: "a" }), h("polyline", { points: "15 11 20.5 7.4 20.5 16.6 15 13" , key: "b" })]),
  at: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 4 , key: "a" }), h("path", { d: "M16 8.4V13.5A2.8 2.8 0 0 0 21 12A9 9 0 1 0 17.2 19.3" , key: "b" })]),
  hash: (p) => svg(p, [h("line", { x1: 4, y1: 9.2, x2: 20, y2: 9.2 , key: "a" }), h("line", { x1: 4, y1: 15.4, x2: 20, y2: 15.4 , key: "b" }), h("line", { x1: 10.4, y1: 3.6, x2: 8.2, y2: 20.4 , key: "c" }), h("line", { x1: 16.6, y1: 3.6, x2: 14.4, y2: 20.4 , key: "d" })]),
  share: (p) => svg(p, [h("circle", { cx: 6, cy: 12, r: 2.6 , key: "a" }), h("circle", { cx: 18, cy: 6.5, r: 2.6 , key: "b" }), h("circle", { cx: 18, cy: 17.5, r: 2.6 , key: "c" }), h("line", { x1: 8.4, y1: 10.9, x2: 15.6, y2: 7.6 , key: "d" }), h("line", { x1: 8.4, y1: 13.1, x2: 15.6, y2: 16.4 , key: "e" })]),
  reply: (p) => svg(p, [h("polyline", { points: "8 5.5 3.5 10 8 14.5" , key: "a" }), h("path", { d: "M3.5 10H15A5.5 5.5 0 0 1 15 21H10" , key: "b" })]),
  inbox: (p) => svg(p, [h("path", { d: "M3.5 13H8.5L10 16H14L15.5 13H20.5" , key: "a" }), h("path", { d: "M3.5 13 6.5 4.5H17.5L20.5 13V18.5A1.5 1.5 0 0 1 19 20H5A1.5 1.5 0 0 1 3.5 18.5Z" , key: "b" })]),
  draft: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V13" , key: "a" }), h("path", { d: "M5.5 3V21H12" , key: "b" }), h("line", { x1: 8.5, y1: 11, x2: 15, y2: 11 , key: "c" }), h("path", { d: "M19.4 13.9 14.6 18.7V20.5H16.4L21.2 15.7Z" , key: "d" })]),
  image: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("polyline", { points: "4.5 17 9.6 11.2 13.5 15.6 15.9 13.1 19.5 17" , key: "b" }), h("rect", { x: 6.4, y: 7.6, width: 2, height: 2 , key: "c" })]),
  images: (p) => svg(p, [h("path", { d: "M7 8.5A1.5 1.5 0 0 1 8.5 7H19.5A1.5 1.5 0 0 1 21 8.5V17.5A1.5 1.5 0 0 1 19.5 19H8.5A1.5 1.5 0 0 1 7 17.5Z" , key: "a" }), h("polyline", { points: "8 17.5 11.7 13.4 14.5 16.5 16.3 14.6 19.6 17.9" , key: "b" }), h("path", { d: "M4 16.5V6.5A1.5 1.5 0 0 1 5.5 5H16" , key: "c" })]),
  camera: (p) => svg(p, [h("path", { d: "M3.5 9A1.5 1.5 0 0 1 5 7.5H8L9.5 5H14.5L16 7.5H19A1.5 1.5 0 0 1 20.5 9V18A1.5 1.5 0 0 1 19 19.5H5A1.5 1.5 0 0 1 3.5 18Z" , key: "a" }), h("circle", { cx: 12, cy: 13, r: 3.6 , key: "b" })]),
  video: (p) => svg(p, [h("path", { d: "M3 6H14A2 2 0 0 1 16 8V16A2 2 0 0 1 14 18H5A2 2 0 0 1 3 16Z" , key: "a" }), h("polyline", { points: "16 11 20.5 8 20.5 16 16 13" , key: "b" })]),
  mic: (p) => svg(p, [h("path", { d: "M12 3.5A2.6 2.6 0 0 1 14.6 6.1V12A2.6 2.6 0 0 1 9.4 12V6.1A2.6 2.6 0 0 1 12 3.5Z" , key: "a" }), h("path", { d: "M6.5 11.5V12.5A5.5 5.5 0 0 0 17.5 12.5V11.5" , key: "b" }), h("line", { x1: 12, y1: 18, x2: 12, y2: 20.5 , key: "c" }), h("line", { x1: 8.5, y1: 20.5, x2: 15.5, y2: 20.5 , key: "d" })]),
  micOff: (p) => svg(p, [h("path", { d: "M14.6 8.5V6.1A2.6 2.6 0 0 0 9.6 5.2" , key: "a" }), h("path", { d: "M9.4 10.2V12A2.6 2.6 0 0 0 13.9 13.8" , key: "b" }), h("path", { d: "M6.5 11.5V12.5A5.5 5.5 0 0 0 15.3 16.9" , key: "c" }), h("path", { d: "M17.5 11.5V12.5" , key: "d" }), h("line", { x1: 12, y1: 18, x2: 12, y2: 20.5 , key: "e" }), h("line", { x1: 8.5, y1: 20.5, x2: 15.5, y2: 20.5 , key: "f" }), h("line", { x1: 4.5, y1: 4.5, x2: 19.5, y2: 17.09 , key: "g" })]),
  volume: (p) => svg(p, [h("polyline", { points: "3.5 9.5 7 9.5 11.5 5.5 11.5 18.5 7 14.5 3.5 14.5" , key: "a" }), h("path", { d: "M15 9.5A4 4 0 0 1 15 14.5" , key: "b" }), h("path", { d: "M17.8 6.7A8 8 0 0 1 17.8 17.3" , key: "c" })]),
  volumeOff: (p) => svg(p, [h("polyline", { points: "3.5 9.5 7 9.5 11.5 5.5 11.5 18.5 7 14.5 3.5 14.5" , key: "a" }), h("line", { x1: 15.5, y1: 9.6, x2: 20.5, y2: 13.8 , key: "b" }), h("line", { x1: 20.5, y1: 9.6, x2: 15.5, y2: 13.8 , key: "c" })]),
  pause: (p) => svg(p, [h("line", { x1: 9, y1: 5, x2: 9, y2: 19 , key: "a" }), h("line", { x1: 15, y1: 5, x2: 15, y2: 19 , key: "b" })]),
  skipBack: (p) => svg(p, [h("polyline", { points: "17 5.5 7 12 17 18.5" , key: "a" }), h("line", { x1: 5.5, y1: 5.5, x2: 5.5, y2: 18.5 , key: "b" })]),
  skipForward: (p) => svg(p, [h("polyline", { points: "7 5.5 17 12 7 18.5" , key: "a" }), h("line", { x1: 18.5, y1: 5.5, x2: 18.5, y2: 18.5 , key: "b" })]),
  record: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("circle", { cx: 12, cy: 12, r: 4, fill: "currentColor", stroke: "none", key: "b" })]),
  help: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("path", { d: "M9.4 9.6A2.7 2.7 0 0 1 14.7 10.3C14.7 12.2 12 12.6 12 14.4" , key: "b" }), h("rect", { x: 11, y: 16.6, width: 2, height: 2 , key: "c" })]),
  question: (p) => svg(p, [h("path", { d: "M9.4 8.4A2.9 2.9 0 0 1 15 9.2C15 11.3 12 11.8 12 13.8" , key: "a" }), h("rect", { x: 11, y: 16.6, width: 2, height: 2 , key: "b" })]),
  alert: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("line", { x1: 12, y1: 7.6, x2: 12, y2: 13 , key: "b" }), h("rect", { x: 11, y: 15.4, width: 2, height: 2 , key: "c" })]),
  bug: (p) => svg(p, [h("path", { d: "M7.5 7.5H12.5A4 4 0 0 1 16.5 11.5V14.5A4 4 0 0 1 12.5 18.5H11.5A4 4 0 0 1 7.5 14.5Z" , key: "a" }), h("line", { x1: 9.5, y1: 4.5, x2: 10.8, y2: 7.5 , key: "b" }), h("line", { x1: 14.5, y1: 4.5, x2: 13.2, y2: 7.5 , key: "c" }), h("line", { x1: 3.5, y1: 11, x2: 7.5, y2: 11 , key: "d" }), h("line", { x1: 16.5, y1: 11, x2: 20.5, y2: 11 , key: "e" }), h("line", { x1: 3.5, y1: 15.5, x2: 7.5, y2: 15.5 , key: "f" }), h("line", { x1: 16.5, y1: 15.5, x2: 20.5, y2: 15.5 , key: "g" }), h("line", { x1: 12, y1: 10, x2: 12, y2: 16 , key: "h" })]),
  verified: (p) => svg(p, [h("path", { d: "M12 3.6 14.4 5.8 17.6 5.4 18 8.6 20.3 10.8 18.7 13.6 19.4 16.7 16.3 17.6 14.6 20.3 11.7 19 8.8 19.9 7.4 17.1 4.3 16.1 5.3 13 3.8 10.3 6.2 8.2 6.7 5.1 9.9 5.4Z" , key: "a" }), h("polyline", { points: "8.6 12.1 10.9 14.03 15.4 10.25" , key: "b" })]),
  pending: (p) => svg(p, [h("path", { d: "M3.5 12A8.5 8.5 0 1 1 20.5 12A8.5 8.5 0 1 1 3.5 12" , key: "a" }), h("rect", { x: 6.6, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "b" }), h("rect", { x: 11, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "c" }), h("rect", { x: 15.4, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none" , key: "d" })]),
  blocked: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("line", { x1: 6, y1: 18, x2: 18, y2: 6 , key: "b" })]),
  circleCheck: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("polyline", { points: "8.3 12.1 10.6 14.03 15.5 9.92" , key: "b" })]),
  circleX: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("line", { x1: 9, y1: 9, x2: 15, y2: 15 , key: "b" }), h("line", { x1: 15, y1: 9, x2: 9, y2: 15 , key: "c" })]),
  circlePlus: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("line", { x1: 12, y1: 8, x2: 12, y2: 16 , key: "b" }), h("line", { x1: 8, y1: 12, x2: 16, y2: 12 , key: "c" })]),
  circleMinus: (p) => svg(p, [h("circle", { cx: 12, cy: 12, r: 8.5 , key: "a" }), h("line", { x1: 8, y1: 12, x2: 16, y2: 12 , key: "b" })]),
  dot: (p) => svg(p, h("rect", { x: 9, y: 9, width: 6, height: 6, fill: "currentColor", stroke: "none", key: "a" })),
  card: (p) => svg(p, [h("path", { d: "M3 5.5H19A2 2 0 0 1 21 7.5V16.5A2 2 0 0 1 19 18.5H5A2 2 0 0 1 3 16.5Z" , key: "a" }), h("line", { x1: 3, y1: 10, x2: 21, y2: 10 , key: "b" }), h("line", { x1: 6.5, y1: 14.5, x2: 10.5, y2: 14.5 , key: "c" })]),
  wallet: (p) => svg(p, [h("path", { d: "M3.5 7.5A2 2 0 0 1 5.5 5.5H17V8" , key: "a" }), h("path", { d: "M3.5 7.5V17.5A2 2 0 0 0 5.5 19.5H19A1.5 1.5 0 0 0 20.5 18V9.5A1.5 1.5 0 0 0 19 8H3.5" , key: "b" }), h("rect", { x: 15.5, y: 12, width: 2.4, height: 2.4 , key: "c" })]),
  receipt: (p) => svg(p, [h("path", { d: "M6 3.5H18V21L15.6 19.2 13.2 21 10.8 19.2 8.4 21 6 19.2Z" , key: "a" }), h("line", { x1: 9, y1: 8.5, x2: 15, y2: 8.5 , key: "b" }), h("line", { x1: 9, y1: 12.5, x2: 15, y2: 12.5 , key: "c" })]),
  tag: (p) => svg(p, [h("path", { d: "M11.4 3.5H20.5V12.6L12.2 20.9A1.5 1.5 0 0 1 10.1 20.9L3.1 13.9A1.5 1.5 0 0 1 3.1 11.8Z" , key: "a" }), h("rect", { x: 16, y: 6.6, width: 2, height: 2 , key: "b" })]),
  cart: (p) => svg(p, [h("polyline", { points: "3 4.5 6 4.5 8.3 15.5 18.5 15.5 20.5 8 7 8" , key: "a" }), h("rect", { x: 8, y: 18, width: 2, height: 2 , key: "b" }), h("rect", { x: 16.5, y: 18, width: 2, height: 2 , key: "c" })]),
  percent: (p) => svg(p, [h("circle", { cx: 7.5, cy: 7.5, r: 2.8 , key: "a" }), h("circle", { cx: 16.5, cy: 16.5, r: 2.8 , key: "b" }), h("line", { x1: 18, y1: 6, x2: 6, y2: 18 , key: "c" })]),
  coins: (p) => svg(p, [h("path", { d: "M3.5 8.5A4.5 2.5 0 0 1 12.5 8.5A4.5 2.5 0 0 1 3.5 8.5" , key: "a" }), h("path", { d: "M3.5 8.5V13A4.5 2.5 0 0 0 12.5 13V8.5" , key: "b" }), h("path", { d: "M11.5 15.5A4.5 2.5 0 0 0 20.5 15.5V11A4.5 2.5 0 0 0 13 9.1" , key: "c" })]),
  bank: (p) => svg(p, [h("polyline", { points: "3 9.5 12 4 21 9.5" , key: "a" }), h("line", { x1: 3, y1: 20.5, x2: 21, y2: 20.5 , key: "b" }), h("line", { x1: 6.5, y1: 12, x2: 6.5, y2: 18 , key: "c" }), h("line", { x1: 12, y1: 12, x2: 12, y2: 18 , key: "d" }), h("line", { x1: 17.5, y1: 12, x2: 17.5, y2: 18 , key: "e" })]),
  invoice: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("line", { x1: 8.5, y1: 12, x2: 15.5, y2: 12 , key: "c" }), h("line", { x1: 8.5, y1: 15, x2: 13, y2: 15 , key: "d" }), h("line", { x1: 12, y1: 17.5, x2: 15.5, y2: 17.5 , key: "e" })]),
  arrowUp: (p) => svg(p, [h("line", { x1: 12, y1: 19, x2: 12, y2: 5 , key: "a" }), h("polyline", { points: "14.7 8.22 12 5 9.3 8.22" , key: "b" })]),
  arrowUpLeft: (p) => svg(p, [h("line", { x1: 17.36, y1: 16.5, x2: 6.64, y2: 7.5 , key: "a" }), h("polyline", { points: "10.84 7.5 6.64 7.5 7.37 11.64" , key: "b" })]),
  arrowDownLeft: (p) => svg(p, [h("line", { x1: 17.36, y1: 7.5, x2: 6.64, y2: 16.5 , key: "a" }), h("polyline", { points: "7.37 12.36 6.64 16.5 10.84 16.5" , key: "b" })]),
  arrowDownRight: (p) => svg(p, [h("line", { x1: 6.64, y1: 7.5, x2: 17.36, y2: 16.5 , key: "a" }), h("polyline", { points: "13.16 16.5 17.36 16.5 16.63 12.36" , key: "b" })]),
  chevronsRight: (p) => svg(p, [h("polyline", { points: "8.41 14.96 11.93 12 8.41 9.04" , key: "a" }), h("polyline", { points: "14.01 14.96 17.53 12 14.01 9.04" , key: "b" })]),
  chevronsLeft: (p) => svg(p, [h("polyline", { points: "15.59 9.04 12.07 12 15.59 14.96" , key: "a" }), h("polyline", { points: "9.99 9.04 6.47 12 9.99 14.96" , key: "b" })]),
  chevronsUp: (p) => svg(p, [h("polyline", { points: "14.96 15.59 12 12.07 9.04 15.59" , key: "a" }), h("polyline", { points: "14.96 9.99 12 6.47 9.04 9.99" , key: "b" })]),
  chevronsDown: (p) => svg(p, [h("polyline", { points: "9.04 8.41 12 11.93 14.96 8.41" , key: "a" }), h("polyline", { points: "9.04 14.01 12 17.53 14.96 14.01" , key: "b" })]),
  home: (p) => svg(p, [h("path", { d: "M3.5 11.4 12 4.3 20.5 11.4" , key: "a" }), h("path", { d: "M6 9.4V20.3H18V9.4" , key: "b" }), h("line", { x1: 10.3, y1: 20.3, x2: 10.3, y2: 14.8 , key: "c" }), h("line", { x1: 13.7, y1: 20.3, x2: 13.7, y2: 14.8 , key: "d" })]),
  back: (p) => svg(p, [h("line", { x1: 20, y1: 12, x2: 5, y2: 12 , key: "a" }), h("polyline", { points: "8.22 9.3 5 12 8.22 14.7" , key: "b" })]),
  forward: (p) => svg(p, [h("line", { x1: 4, y1: 12, x2: 19, y2: 12 , key: "a" }), h("polyline", { points: "15.78 14.7 19 12 15.78 9.3" , key: "b" })]),
  expand: (p) => svg(p, [h("polyline", { points: "9.5 4 4 4 4 9.5" , key: "a" }), h("polyline", { points: "14.5 20 20 20 20 14.5" , key: "b" }), h("line", { x1: 4, y1: 4, x2: 10, y2: 9.03 , key: "c" }), h("line", { x1: 20, y1: 20, x2: 14, y2: 14.97 , key: "d" })]),
  collapse: (p) => svg(p, [h("polyline", { points: "4 9.5 9.5 9.5 9.5 4" , key: "a" }), h("polyline", { points: "20 14.5 14.5 14.5 14.5 20" , key: "b" }), h("line", { x1: 9.5, y1: 9.5, x2: 4, y2: 4.39 , key: "c" }), h("line", { x1: 14.5, y1: 14.5, x2: 20, y2: 19.61 , key: "d" })]),
  maximize: (p) => svg(p, h("path", { d: "M4 4H18A2 2 0 0 1 20 6V18A2 2 0 0 1 18 20H6A2 2 0 0 1 4 18Z" , key: "a" })),
  minimize: (p) => svg(p, [h("path", { d: "M3.5 4.5H18.5A2 2 0 0 1 20.5 6.5V11.5A2 2 0 0 1 18.5 13.5H5.5A2 2 0 0 1 3.5 11.5Z" , key: "a" }), h("rect", { x: 3.5, y: 17.5, width: 17, height: 3, fill: "currentColor", stroke: "none" , key: "b" })]),
  fullscreen: (p) => svg(p, [h("polyline", { points: "9 4 4 4 4 9" , key: "a" }), h("polyline", { points: "15 4 20 4 20 9" , key: "b" }), h("polyline", { points: "9 20 4 20 4 15" , key: "c" }), h("polyline", { points: "15 20 20 20 20 15" , key: "d" })]),
  sidebar: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("line", { x1: 9.5, y1: 4.5, x2: 9.5, y2: 19.5 , key: "b" })]),
  panelRight: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("line", { x1: 14.5, y1: 4.5, x2: 14.5, y2: 19.5 , key: "b" })]),
  layout: (p) => svg(p, [h("path", { d: "M3 4.5H19A2 2 0 0 1 21 6.5V17.5A2 2 0 0 1 19 19.5H5A2 2 0 0 1 3 17.5Z" , key: "a" }), h("line", { x1: 3, y1: 10, x2: 21, y2: 10 , key: "b" }), h("line", { x1: 11, y1: 10, x2: 11, y2: 19.5 , key: "c" })]),
  fileText: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("line", { x1: 8.5, y1: 12, x2: 15.5, y2: 12 , key: "c" }), h("line", { x1: 8.5, y1: 15.5, x2: 13.5, y2: 15.5 , key: "d" }), h("line", { x1: 8.5, y1: 18.5, x2: 12, y2: 18.5 , key: "e" })]),
  fileCode: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("polyline", { points: "11 13.4 8.7 15.7 11 18" , key: "c" }), h("polyline", { points: "14 13.4 16.3 15.7 14 18" , key: "d" })]),
  fileSheet: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("line", { x1: 8.5, y1: 12.5, x2: 16, y2: 12.5 , key: "c" }), h("line", { x1: 8.5, y1: 16, x2: 16, y2: 16 , key: "d" }), h("line", { x1: 12, y1: 12.5, x2: 12, y2: 19.5 , key: "e" }), h("line", { x1: 8.5, y1: 19.5, x2: 16, y2: 19.5 , key: "f" })]),
  fileImage: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("polyline", { points: "8 18.5 11.2 14.8 13.8 17.8 15.3 16.1 17 18.5" , key: "c" }), h("rect", { x: 8.3, y: 11.3, width: 1.6, height: 1.6 , key: "d" })]),
  fileZip: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("line", { x1: 11.2, y1: 10, x2: 12.8, y2: 10 , key: "c" }), h("line", { x1: 11.2, y1: 13, x2: 12.8, y2: 13 , key: "d" }), h("line", { x1: 11.2, y1: 16, x2: 12.8, y2: 16 , key: "e" }), h("rect", { x: 11.2, y: 18.4, width: 1.6, height: 1.6 , key: "f" })]),
  filePdf: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z" , key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2" , key: "b" }), h("line", { x1: 8.5, y1: 13.5, x2: 15.5, y2: 13.5 , key: "c" }), h("line", { x1: 8.5, y1: 16.5, x2: 12.5, y2: 16.5 , key: "d" })]),
  folder: (p) => svg(p, h("path", { d: "M3 7.5H9.5L11.6 10.3H21V19.5A1.5 1.5 0 0 1 19.5 21H4.5A1.5 1.5 0 0 1 3 19.5Z" , key: "a" })),
  folderOpen: (p) => svg(p, [h("path", { d: "M3 7.5H9.5L11.6 10.3H19V12.5" , key: "a" }), h("path", { d: "M3 7.5V19.5A1.5 1.5 0 0 0 4.5 21H18.6L21.5 12.5H5.9Z" , key: "b" })]),
  folderPlus: (p) => svg(p, [h("path", { d: "M3 7.5H9.5L11.6 10.3H21V19.5A1.5 1.5 0 0 1 19.5 21H4.5A1.5 1.5 0 0 1 3 19.5Z" , key: "a" }), h("line", { x1: 12, y1: 13.2, x2: 12, y2: 18 , key: "b" }), h("line", { x1: 9.6, y1: 15.6, x2: 14.4, y2: 15.6 , key: "c" })]),
  archive: (p) => svg(p, [h("rect", { x: 3, y: 4, width: 18, height: 4.5 , key: "a" }), h("path", { d: "M5 8.5V19.5A1.5 1.5 0 0 0 6.5 21H17.5A1.5 1.5 0 0 0 19 19.5V8.5" , key: "b" }), h("line", { x1: 10, y1: 12.5, x2: 14, y2: 12.5 , key: "c" })]),
  clipboard: (p) => svg(p, [h("path", { d: "M8.5 5H6.5A1.5 1.5 0 0 0 5 6.5V19.5A1.5 1.5 0 0 0 6.5 21H17.5A1.5 1.5 0 0 0 19 19.5V6.5A1.5 1.5 0 0 0 17.5 5H15.5" , key: "a" }), h("rect", { x: 8.5, y: 3, width: 7, height: 4 , key: "b" })]),
  clipboardCheck: (p) => svg(p, [h("path", { d: "M8.5 5H6.5A1.5 1.5 0 0 0 5 6.5V19.5A1.5 1.5 0 0 0 6.5 21H17.5A1.5 1.5 0 0 0 19 19.5V6.5A1.5 1.5 0 0 0 17.5 5H15.5" , key: "a" }), h("rect", { x: 8.5, y: 3, width: 7, height: 4 , key: "b" }), h("polyline", { points: "8.7 13.6 11 15.53 15.5 11.75" , key: "c" })]),
  attachment: (p) => svg(p, h("path", { d: "M17.5 10.8 10.4 17.4A3.6 3.6 0 0 1 5.4 12.2L13.1 5A2.5 2.5 0 0 1 16.6 8.6L9.4 15.3A1.4 1.4 0 0 1 7.5 13.3L13.8 7.5" , key: "a" })),
  save: (p) => svg(p, [h("path", { d: "M4.5 4.5H16L19.5 8V19.5H4.5Z" , key: "a" }), h("rect", { x: 8, y: 4.5, width: 8, height: 4.5 , key: "b" }), h("rect", { x: 8, y: 13, width: 8, height: 6.5 , key: "c" })]),
  duplicate: (p) => svg(p, [h("rect", { x: 8.5, y: 8.5, width: 12, height: 12 , key: "a" }), h("path", { d: "M15.5 5.5H4.5A1 1 0 0 0 3.5 6.5V15.5" , key: "b" })]),
  trash: (p) => svg(p, [h("line", { x1: 3.5, y1: 6.5, x2: 20.5, y2: 6.5 , key: "a" }), h("path", { d: "M6.5 6.5V20A1 1 0 0 0 7.5 21H16.5A1 1 0 0 0 17.5 20V6.5" , key: "b" }), h("path", { d: "M9 6.5V4.5A1 1 0 0 1 10 3.5H14A1 1 0 0 1 15 4.5V6.5" , key: "c" }), h("line", { x1: 10.3, y1: 10.5, x2: 10.3, y2: 17.5 , key: "d" }), h("line", { x1: 13.7, y1: 10.5, x2: 13.7, y2: 17.5 , key: "e" })]),
  restore: (p) => svg(p, [h("path", { d: "M4.5 12A7.5 7.5 0 1 0 7 6.3" , key: "a" }), h("polyline", { points: "3.5 3 3.5 7.3 7.8 7.3" , key: "b" })]),
  bold: (p) => svg(p, [h("path", { d: "M7 4H13.5A4 4 0 0 1 13.5 12H7Z" , key: "a" }), h("path", { d: "M7 12H14.5A4 4 0 0 1 14.5 20H7Z" , key: "b" })]),
  italic: (p) => svg(p, [h("line", { x1: 10, y1: 4.5, x2: 18, y2: 4.5 , key: "a" }), h("line", { x1: 6, y1: 19.5, x2: 14, y2: 19.5 , key: "b" }), h("line", { x1: 14.3, y1: 4.5, x2: 9.7, y2: 19.5 , key: "c" })]),
  underline: (p) => svg(p, [h("path", { d: "M7 4V12.5A5 5 0 0 0 17 12.5V4" , key: "a" }), h("line", { x1: 5.5, y1: 20.5, x2: 18.5, y2: 20.5 , key: "b" })]),
  strikethrough: (p) => svg(p, [h("path", { d: "M16 7.2A4 4 0 0 0 8.2 8.1C8.2 10.5 10.6 11.2 13 11.8", key: "a" }), h("path", { d: "M8 16.8A4 4 0 0 0 15.8 15.9C15.8 14.2 14.7 13.2 13 12.6", key: "b" }), h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12, key: "c" })]),
  list: (p) => svg(p, [h("line", { x1: 9, y1: 6.5, x2: 20.5, y2: 6.5 , key: "a" }), h("line", { x1: 9, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 9, y1: 17.5, x2: 20.5, y2: 17.5 , key: "c" }), h("rect", { x: 3.5, y: 5.5, width: 2, height: 2 , key: "d" }), h("rect", { x: 3.5, y: 11, width: 2, height: 2 , key: "e" }), h("rect", { x: 3.5, y: 16.5, width: 2, height: 2 , key: "f" })]),
  listOrdered: (p) => svg(p, [h("line", { x1: 9.5, y1: 6.5, x2: 20.5, y2: 6.5 , key: "a" }), h("line", { x1: 9.5, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 9.5, y1: 17.5, x2: 20.5, y2: 17.5 , key: "c" }), h("polyline", { points: "3.5 5 5 4.4 5 8" , key: "d" }), h("path", { d: "M3.5 10.5H6V13H3.5V15.5H6" , key: "e" })]),
  indent: (p) => svg(p, [h("line", { x1: 10, y1: 6.5, x2: 20.5, y2: 6.5 , key: "a" }), h("line", { x1: 10, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 10, y1: 17.5, x2: 20.5, y2: 17.5 , key: "c" }), h("polyline", { points: "3.5 9 6.4 12 3.5 15" , key: "d" })]),
  outdent: (p) => svg(p, [h("line", { x1: 10, y1: 6.5, x2: 20.5, y2: 6.5 , key: "a" }), h("line", { x1: 10, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 10, y1: 17.5, x2: 20.5, y2: 17.5 , key: "c" }), h("polyline", { points: "6.4 9 3.5 12 6.4 15" , key: "d" })]),
  alignLeft: (p) => svg(p, [h("line", { x1: 3.5, y1: 6, x2: 20.5, y2: 6 , key: "a" }), h("line", { x1: 3.5, y1: 12, x2: 14, y2: 12 , key: "b" }), h("line", { x1: 3.5, y1: 18, x2: 17, y2: 18 , key: "c" })]),
  alignCenter: (p) => svg(p, [h("line", { x1: 3.5, y1: 6, x2: 20.5, y2: 6 , key: "a" }), h("line", { x1: 7, y1: 12, x2: 17, y2: 12 , key: "b" }), h("line", { x1: 5, y1: 18, x2: 19, y2: 18 , key: "c" })]),
  alignRight: (p) => svg(p, [h("line", { x1: 3.5, y1: 6, x2: 20.5, y2: 6 , key: "a" }), h("line", { x1: 10, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 7, y1: 18, x2: 20.5, y2: 18 , key: "c" })]),
  alignJustify: (p) => svg(p, [h("line", { x1: 3.5, y1: 6, x2: 20.5, y2: 6 , key: "a" }), h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12 , key: "b" }), h("line", { x1: 3.5, y1: 18, x2: 20.5, y2: 18 , key: "c" })]),
  undo: (p) => svg(p, [h("path", { d: "M4 10.5H15A5 5 0 0 1 15 20.5H8" , key: "a" }), h("polyline", { points: "7.6 6.4 3.5 10.5 7.6 14.6" , key: "b" })]),
  redo: (p) => svg(p, [h("path", { d: "M20 10.5H9A5 5 0 0 0 9 20.5H16" , key: "a" }), h("polyline", { points: "16.4 6.4 20.5 10.5 16.4 14.6" , key: "b" })]),
  crop: (p) => svg(p, [h("line", { x1: 6.5, y1: 3, x2: 6.5, y2: 17.5 , key: "a" }), h("line", { x1: 3, y1: 6.5, x2: 17.5, y2: 6.5 , key: "b" }), h("polyline", { points: "6.5 17.5 17.5 17.5 17.5 6.5" , key: "c" }), h("line", { x1: 17.5, y1: 17.5, x2: 17.5, y2: 21 , key: "d" }), h("line", { x1: 21, y1: 17.5, x2: 17.5, y2: 17.5 , key: "e" })]),
  door: (p) => svg(p, [h("path", { d: "M4.5 20.5 V6 L14 3.5 V20.5", key: "a" }), h("line", { x1: 3, y1: 20.5, x2: 21, y2: 20.5, key: "b" }), h("line", { x1: 16.5, y1: 13.5, x2: 21, y2: 9.72, key: "c" }), h("line", { x1: 16.5, y1: 17, x2: 21, y2: 13.22, key: "d" })]),
  threshold: (p) => svg(p, [h("line", { x1: 9.5, y1: 3, x2: 9.5, y2: 21, key: "a" }), h("line", { x1: 12, y1: 10, x2: 17, y2: 5.8, key: "b" }), h("line", { x1: 12, y1: 14, x2: 18, y2: 8.97, key: "c" }), h("line", { x1: 12, y1: 18, x2: 17, y2: 13.8, key: "d" })]),
  passport: (p) => svg(p, [h("path", { d: "M4.5 3 H17.5 A2 2 0 0 1 19.5 5 V19 A2 2 0 0 1 17.5 21 H6.5 A2 2 0 0 1 4.5 19 Z", key: "a" }), h("path", { d: "M9 9.5 A3 3 0 1 1 15 9.5 A3 3 0 1 1 9 9.5", key: "b" }), h("line", { x1: 8.5, y1: 15.5, x2: 15.5, y2: 15.5, key: "c" }), h("line", { x1: 8.5, y1: 18.2, x2: 13.2, y2: 18.2, key: "d" })]),
  check: (p) => svg(p, h("polyline", { points: "4.5 11.75 9.5 15.95 19.5 7.56", key: "a" })),
  minus: (p) => svg(p, h("line", { x1: 5, y1: 12, x2: 19, y2: 12, key: "a" })),
  plus: (p) => svg(p, [h("line", { x1: 12, y1: 5, x2: 12, y2: 19, key: "a" }), h("line", { x1: 5, y1: 12, x2: 19, y2: 12, key: "b" })]),
  close: (p) => svg(p, [h("line", { x1: 5.5, y1: 5.5, x2: 18.5, y2: 18.5, key: "a" }), h("line", { x1: 18.5, y1: 5.5, x2: 5.5, y2: 18.5, key: "b" })]),
  chevronDown: (p) => svg(p, h("polyline", { points: "7 9.9 12 14.1 17 9.9", key: "a" })),
  chevronUp: (p) => svg(p, h("polyline", { points: "7 14.1 12 9.9 17 14.1", key: "a" })),
  chevronLeft: (p) => svg(p, h("polyline", { points: "14.1 7 9.9 12 14.1 17", key: "a" })),
  chevronRight: (p) => svg(p, h("polyline", { points: "9.9 7 14.1 12 9.9 17", key: "a" })),
  arrowRight: (p) => svg(p, [h("line", { x1: 3.5, y1: 12, x2: 19.5, y2: 12, key: "a" }), h("polyline", { points: "15.1 8.31 19.5 12 15.1 15.69", key: "b" })]),
  arrowLeft: (p) => svg(p, [h("line", { x1: 20.5, y1: 12, x2: 4.5, y2: 12, key: "a" }), h("polyline", { points: "8.9 8.31 4.5 12 8.9 15.69", key: "b" })]),
  arrowUpRight: (p) => svg(p, [h("line", { x1: 5.2, y1: 17.6, x2: 18.2, y2: 6.69, key: "a" }), h("polyline", { points: "12.46 6.69 18.2 6.69 17.2 12.34", key: "b" })]),
  arrowDown: (p) => svg(p, [h("line", { x1: 12, y1: 3.5, x2: 12, y2: 19.5, key: "a" }), h("polyline", { points: "8.31 15.1 12 19.5 15.69 15.1", key: "b" })]),
  external: (p) => svg(p, [h("polyline", { points: "13.5 4.5 19.5 4.5 19.5 10.5", key: "a" }), h("line", { x1: 19.5, y1: 4.5, x2: 11, y2: 11.63, key: "b" }), h("path", { d: "M16 14.5V19.5H4.5V8H9.5", key: "c" })]),
  search: (p) => svg(p, [h("path", { d: "M12.84 16.02 A6 6 0 1 1 16.35 11.85", key: "a" }), h("line", { x1: 15.1, y1: 14.36, x2: 20.5, y2: 18.89, key: "b" })]),
  info: (p) => svg(p, [h("path", { d: "M20.89 10.59 A9 9 0 1 1 14.93 3.49", key: "a" }), h("rect", { x: 11, y: 7, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "b" }), h("line", { x1: 12, y1: 11, x2: 12, y2: 16.5, key: "c" })]),
  success: (p) => svg(p, [h("path", { d: "M20.89 10.59 A9 9 0 1 1 14.93 3.49", key: "a" }), h("polyline", { points: "8 12.65 10.8 15 16 10.64", key: "b" })]),
  warning: (p) => svg(p, [h("path", { d: "M12 3.5 21.5 20.5 H2.5 Z", key: "a" }), h("line", { x1: 12, y1: 10, x2: 12, y2: 14, key: "b" }), h("rect", { x: 11, y: 16, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" })]),
  danger: (p) => svg(p, [h("path", { d: "M20.89 10.59 A9 9 0 1 1 14.93 3.49", key: "a" }), h("line", { x1: 12, y1: 7, x2: 12, y2: 13, key: "b" }), h("rect", { x: 11, y: 15.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" })]),
  stop: (p) => svg(p, h("rect", { x: 6, y: 6, width: 12, height: 12, fill: "currentColor", stroke: "none" , key: "a" })),
  sparkle: (p) => svg(p, [h("path", { d: "M12 3 L13.9 9.3 L20 12 L13.9 14.7 L12 21 L10.1 14.7 L4 12 L10.1 9.3 Z", key: "a" }), h("line", { x1: 18.5, y1: 4, x2: 20.5, y2: 4, key: "b" }), h("line", { x1: 19.5, y1: 3, x2: 19.5, y2: 5, key: "c" })]),
  tool: (p) => svg(p, [h("path", { d: "M3.5 5.5 H18.5 A2 2 0 0 1 20.5 7.5 V16.5 A2 2 0 0 1 18.5 18.5 H5.5 A2 2 0 0 1 3.5 16.5 Z", key: "a" }), h("line", { x1: 3.5, y1: 9.5, x2: 20.5, y2: 9.5, key: "b" }), h("rect", { x: 5.3, y: 6.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" }), h("rect", { x: 8.1, y: 6.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "d" })]),
  shield: (p) => svg(p, h("path", { d: "M12 3 20 6 V12.5 C20 17 16.4 19.9 12 21.2 C7.6 19.9 4 17 4 12.5 V6 Z", key: "a" })),
  globe: (p) => svg(p, [h("path", { d: "M3 12 A9 9 0 1 1 21 12 A9 9 0 1 1 3 12", key: "a" }), h("line", { x1: 3, y1: 12, x2: 21, y2: 12, key: "b" }), h("path", { d: "M12 3C15.1 5.4 16.6 8.5 16.6 12C16.6 15.5 15.1 18.6 12 21C8.9 18.6 7.4 15.5 7.4 12C7.4 8.5 8.9 5.4 12 3Z", key: "c" })]),
  key: (p) => svg(p, [h("path", { d: "M9.38 11.91 A4.4 4.4 0 1 1 12.12 8.64", key: "a" }), h("line", { x1: 11.17, y1: 10.63, x2: 20.4, y2: 18.37, key: "b" }), h("line", { x1: 17.81, y1: 16.2, x2: 16.14, y2: 18.19, key: "c" }), h("line", { x1: 20.4, y1: 18.37, x2: 19.11, y2: 19.9, key: "d" })]),
  lock: (p) => svg(p, [h("path", { d: "M4.5 10.5 H17.5 A2 2 0 0 1 19.5 12.5 V18.5 A2 2 0 0 1 17.5 20.5 H6.5 A2 2 0 0 1 4.5 18.5 Z", key: "a" }), h("path", { d: "M8 10.5V7.8A4 4 0 0 1 16 7.8V10.5", key: "b" }), h("line", { x1: 12, y1: 14, x2: 12, y2: 17, key: "c" })]),
  unlock: (p) => svg(p, [h("path", { d: "M4.5 10.5 H17.5 A2 2 0 0 1 19.5 12.5 V18.5 A2 2 0 0 1 17.5 20.5 H6.5 A2 2 0 0 1 4.5 18.5 Z", key: "a" }), h("path", { d: "M8 10.5V7.8A4 4 0 0 1 16 7.8", key: "b" }), h("line", { x1: 12, y1: 14, x2: 12, y2: 17, key: "c" })]),
  user: (p) => svg(p, [h("path", { d: "M16.15 7.34 A4.2 4.2 0 1 1 13.37 4.03", key: "a" }), h("path", { d: "M4.5 20.5C4.5 16.9 7.9 14.5 12 14.5C16.1 14.5 19.5 16.9 19.5 20.5", key: "b" })]),
  users: (p) => svg(p, [h("path", { d: "M13.06 7.44 A3.6 3.6 0 1 1 10.67 4.6", key: "a" }), h("path", { d: "M3 20.5C3 17.4 5.9 15.2 9.5 15.2C13.1 15.2 16 17.4 16 20.5", key: "b" }), h("path", { d: "M16.2 5.2A3.6 3.6 0 0 1 16.2 11.9", key: "c" }), h("path", { d: "M17.4 15.6C19.6 16.4 21 18.3 21 20.5", key: "d" })]),
  ladder: (p) => svg(p, [h("line", { x1: 8, y1: 3, x2: 8, y2: 21, key: "a" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 21, key: "b" }), h("line", { x1: 8, y1: 7, x2: 16, y2: 7, key: "c" }), h("line", { x1: 8, y1: 12, x2: 16, y2: 12, key: "d" }), h("line", { x1: 8, y1: 17, x2: 16, y2: 17, key: "e" })]),
  spark: (p) => svg(p, h("path", { d: "M13.5 3 7 13.2 12 13.2 10.5 21 17 10.8 12 10.8 Z", key: "a" })),
  mail: (p) => svg(p, [h("path", { d: "M3 5 H19 A2 2 0 0 1 21 7 V17 A2 2 0 0 1 19 19 H5 A2 2 0 0 1 3 17 Z", key: "a" }), h("polyline", { points: "3 7.5 12 13.5 21 7.5", key: "b" })]),
  file: (p) => svg(p, [h("path", { d: "M5.5 3H14L19 7.2V21H5.5Z", key: "a" }), h("polyline", { points: "14 3 14 7.2 19 7.2", key: "b" }), h("line", { x1: 8.5, y1: 13, x2: 15.5, y2: 13, key: "c" }), h("line", { x1: 8.5, y1: 16.5, x2: 13.5, y2: 16.5, key: "d" })]),
  grid: (p) => svg(p, [h("path", { d: "M3.5 3.5 H9.0 A1.5 1.5 0 0 1 10.5 5.0 V9.0 A1.5 1.5 0 0 1 9.0 10.5 H5.0 A1.5 1.5 0 0 1 3.5 9.0 Z", key: "a" }), h("path", { d: "M13.5 3.5 H19.0 A1.5 1.5 0 0 1 20.5 5.0 V9.0 A1.5 1.5 0 0 1 19.0 10.5 H15.0 A1.5 1.5 0 0 1 13.5 9.0 Z", key: "b" }), h("path", { d: "M3.5 13.5 H9.0 A1.5 1.5 0 0 1 10.5 15.0 V19.0 A1.5 1.5 0 0 1 9.0 20.5 H5.0 A1.5 1.5 0 0 1 3.5 19.0 Z", key: "c" }), h("path", { d: "M13.5 13.5 H19.0 A1.5 1.5 0 0 1 20.5 15.0 V19.0 A1.5 1.5 0 0 1 19.0 20.5 H15.0 A1.5 1.5 0 0 1 13.5 19.0 Z", key: "d" })]),
  chart: (p) => svg(p, [h("line", { x1: 3.5, y1: 20.5, x2: 20.5, y2: 20.5, key: "a" }), h("line", { x1: 7, y1: 20.5, x2: 7, y2: 13, key: "b" }), h("line", { x1: 12, y1: 20.5, x2: 12, y2: 8.5, key: "c" }), h("line", { x1: 17, y1: 20.5, x2: 17, y2: 4, key: "d" })]),
  trend: (p) => svg(p, [h("line", { x1: 3.5, y1: 20.5, x2: 3.5, y2: 3.5, key: "a" }), h("line", { x1: 3.5, y1: 20.5, x2: 20.5, y2: 20.5, key: "b" }), h("polyline", { points: "6.5 16.6 11 12.4 14 13.41 18.6 7.15", key: "c" }), h("polyline", { points: "13.79 8.31 18.6 7.15 18.87 12.14", key: "d" })]),
  clock: (p) => svg(p, [h("path", { d: "M3 12 A9 9 0 1 1 21 12 A9 9 0 1 1 3 12", key: "a" }), h("polyline", { points: "12 6.2 12 12.4 16.6 14.6", key: "b" })]),
  calendar: (p) => svg(p, [h("path", { d: "M3.5 5 H18.5 A2 2 0 0 1 20.5 7 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z", key: "a" }), h("line", { x1: 3.5, y1: 10, x2: 20.5, y2: 10, key: "b" }), h("line", { x1: 8, y1: 3, x2: 8, y2: 7, key: "c" }), h("line", { x1: 16, y1: 3, x2: 16, y2: 7, key: "d" }), h("rect", { x: 7.5, y: 13, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "e" }), h("rect", { x: 11, y: 13, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "f" })]),
  filter: (p) => svg(p, h("polyline", { points: "3.5 5.5 20.5 5.5 13.8 13.2 13.8 19.4 10.2 21 10.2 13.2 3.5 5.5", key: "a" })),
  sort: (p) => svg(p, [h("line", { x1: 4, y1: 6.5, x2: 20, y2: 6.5, key: "a" }), h("line", { x1: 4, y1: 12, x2: 14.5, y2: 12, key: "b" }), h("line", { x1: 4, y1: 17.5, x2: 9, y2: 17.5, key: "c" })]),
  link: (p) => svg(p, [h("path", { d: "M10.5 13.5A4.6 4.6 0 0 0 17 13.5L20 11A4.6 4.6 0 0 0 13.5 4L11.8 5.43", key: "a" }), h("path", { d: "M13.5 10.5A4.6 4.6 0 0 0 7 10.5L4 13A4.6 4.6 0 0 0 10.5 20L12.2 18.57", key: "b" })]),
  upload: (p) => svg(p, [h("line", { x1: 12, y1: 20, x2: 12, y2: 5, key: "a" }), h("polyline", { points: "8.31 9.4 12 5 15.69 9.4", key: "b" }), h("line", { x1: 3.5, y1: 20.5, x2: 20.5, y2: 20.5, key: "c" })]),
  download: (p) => svg(p, [h("line", { x1: 12, y1: 4, x2: 12, y2: 17, key: "a" }), h("polyline", { points: "8.31 12.6 12 17 15.69 12.6", key: "b" }), h("line", { x1: 3.5, y1: 20.5, x2: 20.5, y2: 20.5, key: "c" })]),
  send: (p) => svg(p, [h("path", { d: "M3 12 21 5.51 14.5 21 11.6 13.4 Z", key: "a" }), h("line", { x1: 11.6, y1: 13.4, x2: 21, y2: 5.51, key: "b" })]),
  refresh: (p) => svg(p, [h("path", { d: "M18.77 16.07 A7.9 7.9 0 1 1 18.77 7.93", key: "a" }), h("polyline", { points: "14.61 6.5 18.77 7.93 19.46 3.58", key: "b" })]),
  more: (p) => svg(p, [h("rect", { x: 5, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "a" }), h("rect", { x: 11, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "b" }), h("rect", { x: 17, y: 11, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" })]),
  menu: (p) => svg(p, [h("line", { x1: 3.5, y1: 7, x2: 20.5, y2: 7, key: "a" }), h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12, key: "b" }), h("line", { x1: 3.5, y1: 17, x2: 20.5, y2: 17, key: "c" })]),
  settings: (p) => svg(p, [h("line", { x1: 3.5, y1: 7.5, x2: 20.5, y2: 7.5, key: "a" }), h("line", { x1: 3.5, y1: 16.5, x2: 20.5, y2: 16.5, key: "b" }), h("path", { d: "M7 5.5 H10 A1 1 0 0 1 11 6.5 V8.5 A1 1 0 0 1 10 9.5 H8 A1 1 0 0 1 7 8.5 Z", key: "c" }), h("path", { d: "M13 14.5 H16 A1 1 0 0 1 17 15.5 V17.5 A1 1 0 0 1 16 18.5 H14 A1 1 0 0 1 13 17.5 Z", key: "d" })]),
  eye: (p) => svg(p, [h("path", { d: "M2.5 12C5 8 8.4 6 12 6C15.6 6 19 8 21.5 12C19 16 15.6 18 12 18C8.4 18 5 16 2.5 12Z", key: "a" }), h("path", { d: "M9 12 A3 3 0 1 1 15 12 A3 3 0 1 1 9 12", key: "b" })]),
  star: (p) => svg(p, h("path", { d: "M12 3.2 14.7 9.4 21.4 10.1 16.4 14.6 17.8 21.2 12 17.8 6.2 21.2 7.6 14.6 2.6 10.1 9.3 9.4 Z", key: "a" })),
  bookmark: (p) => svg(p, h("path", { d: "M6 3H18V21L12 15.97 6 21Z", key: "a" })),
  copy: (p) => svg(p, [h("path", { d: "M8 8 H18.5 A2 2 0 0 1 20.5 10 V18.5 A2 2 0 0 1 18.5 20.5 H10 A2 2 0 0 1 8 18.5 Z", key: "a" }), h("path", { d: "M16 8V4.5H3.5V17H7", key: "b" })]),
  edit: (p) => svg(p, [h("path", { d: "M 4.596 18.554 8.6434 17.8578 19.4876 8.7482 16.8208 5.5858 5.9766 14.6954 Z", key: "a" }), h("line", { x1: 13.7882, y1: 8.1346, x2: 16.455, y2: 11.297, key: "b" })]),
  play: (p) => svg(p, h("path", { d: "M 5.5 4.5 18.5 12 5.5 19.5 Z", key: "a" })),
  bridge: (p) => svg(p, [h("line", { x1: 3, y1: 7, x2: 21, y2: 7, key: "a" }), h("path", { d: "M 6.3 18 A 5.7 5.7 0 0 1 17.7 18", key: "b" }), h("line", { x1: 6.3, y1: 7, x2: 6.3, y2: 18, key: "c" }), h("line", { x1: 17.7, y1: 7, x2: 17.7, y2: 18, key: "d" })]),
  translate: (p) => svg(p, [h("polyline", { points: "3 17.5 6.9 7.5 10.8 17.5", key: "a" }), h("line", { x1: 4.7, y1: 13, x2: 9.1, y2: 13, key: "b" }), h("path", { d: "M 13.5 9 H 19.5 A 1.5 1.5 0 0 1 21 10.5 V 16.5 A 1.5 1.5 0 0 1 19.5 18 H 15 A 1.5 1.5 0 0 1 13.5 16.5 Z", key: "c" }), h("line", { x1: 15.55, y1: 12, x2: 19.35, y2: 12, key: "d" }), h("line", { x1: 15.55, y1: 15, x2: 19.35, y2: 15, key: "e" })]),
  beacon: (p) => svg(p, [h("path", { d: "M8.5 6.5 H14.5 A1 1 0 0 1 15.5 7.5 V10.5 A1 1 0 0 1 14.5 11.5 H9.5 A1 1 0 0 1 8.5 10.5 Z", key: "a" }), h("polyline", { points: "9.2 20.5 10.4 11.5 13.6 11.5 14.8 20.5", key: "b" }), h("line", { x1: 6, y1: 20.5, x2: 18, y2: 20.5, key: "c" }), h("line", { x1: 17.2, y1: 8, x2: 21, y2: 4.81, key: "d" }), h("line", { x1: 6.8, y1: 8, x2: 3, y2: 4.81, key: "e" })]),
  seal: (p) => svg(p, [h("path", { d: "M5 10.5 A7 7 0 1 1 19 10.5 A7 7 0 1 1 5 10.5", key: "a" }), h("polyline", { points: "8.8 10.8 11.1 12.73 15.2 9.29", key: "b" }), h("polyline", { points: "9.5 16.6 9.5 21.4 12 19.3 14.5 21.4 14.5 16.6", key: "c" })]),
  clause: (p) => svg(p, [h("path", { d: "M3.5 5 H6.5 A1 1 0 0 1 7.5 6 V8.5 A1 1 0 0 1 6.5 9.5 H4.5 A1 1 0 0 1 3.5 8.5 Z", key: "a" }), h("line", { x1: 10.5, y1: 7.25, x2: 20.5, y2: 7.25, key: "b" }), h("line", { x1: 3.5, y1: 13.5, x2: 20.5, y2: 13.5, key: "c" }), h("line", { x1: 3.5, y1: 17, x2: 20.5, y2: 17, key: "d" }), h("line", { x1: 3.5, y1: 20.5, x2: 15, y2: 20.5, key: "e" })]),
  highlight: (p) => svg(p, [h("line", { x1: 3.5, y1: 5.5, x2: 20.5, y2: 5.5, key: "a" }), h("path", { d: "M3.5 9 H13 A1 1 0 0 1 14 10 V13 A1 1 0 0 1 13 14 H4.5 A1 1 0 0 1 3.5 13 Z", key: "b" }), h("line", { x1: 3.5, y1: 18, x2: 20.5, y2: 18, key: "c" }), h("line", { x1: 3.5, y1: 21, x2: 14, y2: 21, key: "d" })]),
  redact: (p) => svg(p, [h("line", { x1: 3.5, y1: 5.5, x2: 20.5, y2: 5.5, key: "a" }), h("rect", { x: 3.5, y: 9, width: 10.5, height: 5, fill: "currentColor", stroke: "none", key: "b" }), h("line", { x1: 3.5, y1: 18, x2: 20.5, y2: 18, key: "c" }), h("line", { x1: 3.5, y1: 21, x2: 14, y2: 21, key: "d" })]),
  stack: (p) => svg(p, [h("path", { d: "M3.5 12.5 H14.5 A1.5 1.5 0 0 1 16 14 V19 A1.5 1.5 0 0 1 14.5 20.5 H5 A1.5 1.5 0 0 1 3.5 19 Z", key: "a" }), h("polyline", { points: "6.5 9.5 17.5 9.5 17.5 17.5", key: "b" }), h("polyline", { points: "9.5 6.5 20.5 6.5 20.5 14.5", key: "c" })]),
  columns: (p) => svg(p, [h("path", { d: "M3.5 4.5 H18.5 A2 2 0 0 1 20.5 6.5 V17.5 A2 2 0 0 1 18.5 19.5 H5.5 A2 2 0 0 1 3.5 17.5 Z", key: "a" }), h("line", { x1: 3.5, y1: 9, x2: 20.5, y2: 9, key: "b" }), h("line", { x1: 9.17, y1: 9, x2: 9.17, y2: 19.5, key: "c" }), h("line", { x1: 14.83, y1: 9, x2: 14.83, y2: 19.5, key: "d" })]),
  checklist: (p) => svg(p, [h("polyline", { points: "3.5 6.8 5.3 8.31 8.9 5.29", key: "a" }), h("line", { x1: 11.5, y1: 6.5, x2: 20.5, y2: 6.5, key: "b" }), h("polyline", { points: "3.5 12.8 5.3 14.31 8.9 11.29", key: "c" }), h("line", { x1: 11.5, y1: 12.5, x2: 20.5, y2: 12.5, key: "d" }), h("polyline", { points: "3.5 18.8 5.3 20.31 8.9 17.29", key: "e" }), h("line", { x1: 11.5, y1: 18.5, x2: 16.5, y2: 18.5, key: "f" })]),
  signature: (p) => svg(p, [h("path", { d: "M3 16.5 C6 3.5 9.4 3.2 10.2 11.5 C10.9 18.8 13 17.5 15.4 10 C16.8 5.6 19.4 8.4 20.5 13.5", key: "a" }), h("line", { x1: 3, y1: 20.5, x2: 21, y2: 20.5, key: "b" })]),
  scan: (p) => svg(p, [h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12, key: "z" }), h("polyline", { points: "3.5 8 3.5 4.5 7 4.5", key: "a" }), h("polyline", { points: "17 4.5 20.5 4.5 20.5 8", key: "b" }), h("polyline", { points: "20.5 16 20.5 19.5 17 19.5", key: "c" }), h("polyline", { points: "7 19.5 3.5 19.5 3.5 16", key: "d" }), h("line", { x1: 3.5, y1: 12, x2: 20.5, y2: 12, key: "e" })]),
  scales: (p) => svg(p, [h("line", { x1: 6, y1: 7, x2: 18, y2: 7, key: "a" }), h("line", { x1: 12, y1: 4.5, x2: 12, y2: 20, key: "b" }), h("line", { x1: 9, y1: 20, x2: 15, y2: 20, key: "c" }), h("path", { d: "M6 7 V9.8 M3 9.8 H9 L6 14.4 Z", key: "d" }), h("path", { d: "M18 7 V9.8 M15 9.8 H21 L18 14.4 Z", key: "e" })]),
  flag: (p) => svg(p, [h("line", { x1: 5.5, y1: 3, x2: 5.5, y2: 21, key: "a" }), h("path", { d: "M5.5 4.5 H19 L15.5 7.44 19 10.38 H5.5 Z", key: "b" })]),
  compare: (p) => svg(p, [h("path", { d: "M3 5 H8.5 A1.5 1.5 0 0 1 10 6.5 V17.5 A1.5 1.5 0 0 1 8.5 19 H4.5 A1.5 1.5 0 0 1 3 17.5 Z", key: "a" }), h("path", { d: "M14 5 H19.5 A1.5 1.5 0 0 1 21 6.5 V17.5 A1.5 1.5 0 0 1 19.5 19 H15.5 A1.5 1.5 0 0 1 14 17.5 Z", key: "b" }), h("line", { x1: 5, y1: 9.5, x2: 8, y2: 9.5, key: "c" }), h("line", { x1: 16, y1: 9.5, x2: 19, y2: 9.5, key: "d" }), h("line", { x1: 16, y1: 13.5, x2: 19, y2: 13.5, key: "e" })]),
  route: (p) => svg(p, [h("rect", { x: 3, y: 19, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "a" }), h("polyline", { points: "5.5 20 9.5 20 9.5 13 15 13 15 6 20.5 6", key: "b" })]),
  history: (p) => svg(p, [h("path", { d: "M5.23 16.07 A7.9 7.9 0 1 0 5.23 7.93", key: "a" }), h("polyline", { points: "9.39 6.5 5.23 7.93 4.54 3.58", key: "b" }), h("polyline", { points: "12 7 12 12.4 16.3 14.6", key: "c" })]),
  branch: (p) => svg(p, [h("line", { x1: 6.5, y1: 6, x2: 6.5, y2: 18, key: "a" }), h("path", { d: "M6.5 9 H14 A3 3 0 0 1 17 12 V15", key: "b" }), h("rect", { x: 5, y: 3, width: 3, height: 3, fill: "currentColor", stroke: "none", key: "c" }), h("rect", { x: 5, y: 18, width: 3, height: 3, fill: "currentColor", stroke: "none", key: "d" }), h("rect", { x: 15.5, y: 15, width: 3, height: 3, fill: "currentColor", stroke: "none", key: "e" })]),
  briefcase: (p) => svg(p, [h("path", { d: "M3.5 8 H18.5 A2 2 0 0 1 20.5 10 V18.5 A2 2 0 0 1 18.5 20.5 H5.5 A2 2 0 0 1 3.5 18.5 Z", key: "a" }), h("path", { d: "M9 8 V5.5 A1.5 1.5 0 0 1 10.5 4 H13.5 A1.5 1.5 0 0 1 15 5.5 V8", key: "b" }), h("line", { x1: 3.5, y1: 13, x2: 20.5, y2: 13, key: "c" })]),
  building: (p) => svg(p, [h("polyline", { points: "4 20.5 4 4 14 4 14 20.5", key: "a" }), h("polyline", { points: "14 9.5 20.5 9.5 20.5 20.5", key: "b" }), h("line", { x1: 2.5, y1: 20.5, x2: 21.5, y2: 20.5, key: "c" }), h("rect", { x: 6.5, y: 7.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "d" }), h("rect", { x: 10, y: 7.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "e" }), h("rect", { x: 6.5, y: 13, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "f" })]),
  graduation: (p) => svg(p, [h("path", { d: "M2.5 9.5 12 5.5 21.5 9.5 12 13.5 Z", key: "a" }), h("path", { d: "M6.5 11.2 V16.6 C6.5 16.6 8.8 18.6 12 18.6 C15.2 18.6 17.5 16.6 17.5 16.6 V11.2", key: "b" }), h("line", { x1: 20.6, y1: 10.2, x2: 20.6, y2: 15.8, key: "c" })]),
  network: (p) => svg(p, [h("path", { d: "M10 3.5 H13 A1 1 0 0 1 14 4.5 V7 A1 1 0 0 1 13 8 H11 A1 1 0 0 1 10 7 Z", key: "a" }), h("path", { d: "M3 15.5 H6 A1 1 0 0 1 7 16.5 V19 A1 1 0 0 1 6 20 H4 A1 1 0 0 1 3 19 Z", key: "b" }), h("path", { d: "M17 15.5 H20 A1 1 0 0 1 21 16.5 V19 A1 1 0 0 1 20 20 H18 A1 1 0 0 1 17 19 Z", key: "c" }), h("line", { x1: 10.6, y1: 8.6, x2: 5.2, y2: 15, key: "d" }), h("line", { x1: 13.4, y1: 8.6, x2: 18.8, y2: 15, key: "e" })]),
  pin: (p) => svg(p, [h("path", { d: "M5.5 9.5 A6.5 6.5 0 1 1 18.5 9.5 C18.5 14.5 12 21 12 21 C12 21 5.5 14.5 5.5 9.5 Z", key: "a" }), h("path", { d: "M9.5 9.5 A2.5 2.5 0 1 1 14.5 9.5 A2.5 2.5 0 1 1 9.5 9.5", key: "b" })]),
  anonymous: (p) => svg(p, [h("path", { d: "M16.15 7.34 A4.2 4.2 0 1 1 13.37 4.03", key: "a" }), h("path", { d: "M4.5 20.5C4.5 16.9 7.9 14.5 12 14.5C16.1 14.5 19.5 16.9 19.5 20.5", key: "b" }), h("rect", { x: 7.8, y: 6.9, width: 8.4, height: 2.4, fill: "currentColor", stroke: "none", key: "c" })]),
  brush: (p) => svg(p, [h("line", { x1: 20, y1: 4, x2: 14.25, y2: 8.82, key: "a" }), h("polygon", { points: "15.28 10.05 13.36 11.66 8.88 13.32 11.3 9.2 13.22 7.59", key: "b" }), h("line", { x1: 3, y1: 21, x2: 8, y2: 21, key: "c" })]),
  fill: (p) => svg(p, h("path", { d: "M12 5.94 L16.21 10.96 A5.5 5.5 0 1 1 7.79 10.96 Z", key: "a" })),
  rectangle: (p) => svg(p, h("path", { d: "M3.5 6.5H18.5A2 2 0 0 1 20.5 8.5V15.5A2 2 0 0 1 18.5 17.5H5.5A2 2 0 0 1 3.5 15.5Z", key: "a" })),
  ellipse: (p) => svg(p, h("path", { d: "M3.5 12A8.5 6 0 1 1 20.5 12A8.5 6 0 1 1 3.5 12", key: "a" })),
  shape: (p) => svg(p, [h("path", { d: "M5 18C7 6 17 6 19 18", key: "a" }), h("rect", { x: 4, y: 18.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "b" }), h("rect", { x: 18, y: 18.5, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" })]),
  gradient: (p) => svg(p, h("polygon", { points: "3.5 20.5 20.5 20.5 20.5 6.24", key: "a" })),
  transform: (p) => svg(p, [h("rect", { x: 4, y: 4, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "a" }), h("rect", { x: 18, y: 4, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "b" }), h("rect", { x: 18, y: 18, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "c" }), h("rect", { x: 4, y: 18, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "d" }), h("line", { x1: 7.5, y1: 5, x2: 16.5, y2: 5, key: "e" }), h("line", { x1: 19, y1: 7.5, x2: 19, y2: 16.5, key: "f" }), h("line", { x1: 16.5, y1: 19, x2: 7.5, y2: 19, key: "g" }), h("line", { x1: 5, y1: 16.5, x2: 5, y2: 7.5, key: "h" })]),
  eyedropper: (p) => svg(p, [h("line", { x1: 15.5, y1: 8.5, x2: 19.33, y2: 5.29, key: "a" }), h("line", { x1: 17.56, y1: 10.95, x2: 13.44, y2: 6.05, key: "b" }), h("line", { x1: 15.5, y1: 8.5, x2: 8.22, y2: 14.61, key: "c" }), h("rect", { x: 5.46, y: 15.09, width: 2, height: 2, fill: "currentColor", stroke: "none", key: "d" })]),
};

export const iconNames = Object.keys(icons) as IconName[];

export default icons;
