#!/usr/bin/env node
'use strict';
/**
 * Generates `src/icons/index.tsx` from the icon table in the design system's reference bundle.
 *
 * The table is 252 glyphs of path data. Retyping it by hand would introduce exactly the class of
 * error nobody reviews - one wrong coordinate in one path - so it is transcribed mechanically and
 * the parity harness renders every glyph against the reference.
 *
 * Only the wrapper is ours: the geometry is carried across verbatim.
 *
 *   node tools/generate/icons.js          writes the file
 *   node tools/generate/icons.js --check  fails if the file is out of date
 */

const fs = require('fs');
const path = require('path');

const SYSTEM = process.env.REDROB_DS_DIR || '/home/ubuntu/workplace/redrob-design-system';
const BUNDLE = path.join(SYSTEM, 'components', 'bundle.js');
const OUT = path.join(__dirname, '..', '..', 'src', 'icons', 'index.tsx');

const lines = fs.readFileSync(BUNDLE, 'utf8').split('\n');

const start = lines.findIndex((l) => l.trim() === 'var Icons = {');
if (start === -1) throw new Error('icon table not found in the reference bundle');
let end = -1;
for (let i = start + 1; i < lines.length; i++) {
  if (lines[i] === '  };') { end = i; break; }
}
if (end === -1) throw new Error('icon table has no terminator');

const body = lines.slice(start + 1, end);

/** `name: function (p) { return svg(p, [...]); },` -> the name and the children expression. */
const entries = [];
let inComment = false;
for (const raw of body) {
  const line = raw.trim();
  // The table carries multi-line prose about the glyph families. Track the comment state rather
  // than pattern-matching each line: a continuation line starts with an ordinary word, so a
  // per-line test reads it as a malformed entry.
  if (inComment) {
    if (line.includes('*/')) inComment = false;
    continue;
  }
  if (line.startsWith('/*')) {
    if (!line.includes('*/')) inComment = true;
    continue;
  }
  if (line === '' || line.startsWith('//')) continue;
  const match = /^([A-Za-z0-9_]+): function \(p\) \{ return svg\(p, (.*)\); \},$/.exec(line);
  if (!match) throw new Error(`unrecognised icon line, refusing to guess: ${line.slice(0, 80)}`);
  entries.push({ name: match[1], children: match[2] });
}

const header = `// Redrob icons - ${entries.length} glyphs.
//
// Generated by tools/generate/icons.js from the design system's reference bundle. The path geometry
// is transcribed, not rewritten: 24px box, 20px live area, 2px stroke, butt caps, miter joins, and
// every chevron, arrowhead and slash on the logo's 40 degree rake. Edit the design system and
// regenerate; a hand edit here is overwritten.
//
// Do not add a glyph from Feather, Lucide or any framework default. This set is the brand's own.

import * as React from 'react';

export type IconProps = React.SVGProps<SVGSVGElement>;

/** Every glyph shares this frame, so a glyph only carries its own geometry. */
export function svg(props: IconProps, children: React.ReactNode): React.ReactElement {
  return React.createElement(
    'svg',
    {
      viewBox: '0 0 24 24',
      width: '1em',
      height: '1em',
      fill: 'none',
      stroke: 'currentColor',
      strokeWidth: 2,
      strokeLinecap: 'butt',
      strokeLinejoin: 'miter',
      strokeMiterlimit: 3,
      'aria-hidden': 'true',
      focusable: 'false',
      ...props,
    },
    children,
  );
}

const h = React.createElement;

export type IconName =
${entries.map((e) => `  | '${e.name}'`).join('\n')};

export type IconComponent = (props: IconProps) => React.ReactElement;

export const icons: Record<IconName, IconComponent> = {
`;

const table = entries
  .map((e) => `  ${e.name}: (p) => svg(p, ${e.children}),`)
  .join('\n');

const footer = `
};

export const iconNames = Object.keys(icons) as IconName[];

export default icons;
`;

const out = header + table + footer;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error(`src/icons/index.tsx is out of date. Run: node tools/generate/icons.js`);
    process.exit(1);
  }
  console.log(`icons up to date (${entries.length} glyphs)`);
} else {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  console.log(`wrote ${OUT} - ${entries.length} glyphs`);
}
